### PR TITLE
Remove direct dependency on `curl`

### LINKED ISSUE #567: Sway depends on openssl
Running `cargo install forc` on a fresh Ubuntu install reveals it needs the `openssl-sys` dependency, which require the openssl system library.

```
error: failed to run custom build command for `openssl-sys v0.9.72`

Caused by:
  process didn't exit successfully: `/tmp/cargo-install3xS11j/release/build/openssl-sys-0597f39ed250f8ab/build-script-main` (exit status: 101)
  --- stdout
  cargo:rustc-cfg=const_fn
  cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR
  X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
  OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR
  X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
  OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_DIR
  X86_64_UNKNOWN_LINUX_GNU_OPENSSL_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_DIR
  OPENSSL_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=OPENSSL_STATIC
  cargo:rerun-if-env-changed=OPENSSL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  run pkg_config fail: "`\"pkg-config\" \"--libs\" \"--cflags\" \"openssl\"` did not exit successfully: exit status: 1\nerror: could not find system library 'openssl' required by the 'openssl-sys' crate\n\n--- stderr\nPackage openssl was not found in the pkg-config search path.\nPerhaps you should add the directory containing `openssl.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package 'openssl' found\n"

  --- stderr
  thread 'main' panicked at '

  Could not find directory of OpenSSL installation, and this `-sys` crate cannot
  proceed without this knowledge. If OpenSSL is installed and this crate had
  trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
  compilation process.

  Make sure you also have the development packages of openssl installed.
  For example, `libssl-dev` on Ubuntu or `openssl-devel` on Fedora.

  If you're in a situation where you think the directory *should* be found
  automatically, please open a bug at https://github.com/sfackler/rust-openssl
  and include information about your system as well as this message.
```

A note to install openssl should probably be added to the install section of The Book and also in the readme. Alternatively, we should figure out if we can remove openssl as a dependency, as I don't see why installing `forc` itself should have any use of openssl.

### PR DESCRIPTION
**Pull request by adlerjohn**
Fixes #567

1. Use the `rustls-tls` feature for `reqwest` and turn off default features (which would use native OpenSSL).
2. Use `ureq` instead of `curl`.

### CODE REVIEW

**Comment by adlerjohn** [comment]
`openssl-sys` is still required by `fuel-gql-client`, but is no longer required directly by `forc`:

```console
$ cargo tree --invert openssl-sys
openssl-sys v0.9.72
├── curl v0.4.42
│   └── isahc v0.9.14
│       └── http-client v6.5.1
│           └── surf v2.3.2
│               ├── cynic v0.14.1
│               │   └── fuel-gql-client v0.1.2
│               │       └── forc v0.2.1 (/home/devel/local/fuellabs/sway/forc)
│               │           └── test v0.2.1 (/home/devel/local/fuellabs/sway/test)
│               └── fuel-gql-client v0.1.2 (*)
└── curl-sys v0.4.52+curl-7.81.0
    ├── curl v0.4.42 (*)
    └── isahc v0.9.14 (*)

```

File: forc/src/ops/forc_abi_json.rs [hunk 1]
```diff
@@ -8,6 +8,7 @@ use crate::{
     },
 };
 
+use futures::executor::block_on;
```
Comment (leviathanbeak) [inline forc/src/ops/forc_abi_json.rs:11]: we are already using tokio's executor (in the main.rs - it's abstracted in the macro `#[tokio::main]`) the last thing we should do is add another executor

File: forc/src/ops/forc_abi_json.rs [hunk 2]
```diff
@@ -72,13 +73,13 @@ pub fn build(command: JsonAbiCommand) -> Result<Value, String> {
             // Download a non-local dependency if the `git` property is set in this dependency.
             if let Some(git) = &dep.git {
                 let fully_qualified_dep_name = format!("{}-{}", dependency_name, git);
-                let downloaded_dep_path = match dependency::download_github_dep(
+                let downloaded_dep_path = match block_on(dependency::download_github_dep(
```
Comment (leviathanbeak) [inline forc/src/ops/forc_abi_json.rs:76]: you can make these functions `async` as well - just be careful to correctly handle the recursion since some of them are recursive,

if possible avoid the recursion
if not possible there are ways to get around it

Comment (leviathanbeak) [inline forc/src/ops/forc_abi_json.rs:76]:
```suggestion
                let downloaded_dep_path = match dependency::download_github_dep(
```

File: forc/src/ops/forc_abi_json.rs [hunk 3]
```diff
@@ -72,13 +73,13 @@ pub fn build(command: JsonAbiCommand) -> Result<Value, String> {
...
                     &fully_qualified_dep_name,
                     git,
                     &dep.branch,
                     &dep.version,
                     offline_mode.into(),
-                ) {
+                )) {
```
Comment (leviathanbeak) [inline forc/src/ops/forc_abi_json.rs:82]:
```suggestion
                ).await {
```

**Comment by leviathanbeak** [comment]
are we ok with having two http clients? one blocking (ureq) and the other non-blocking (reqwest)

**Comment by adlerjohn** [comment]
> are we ok with having two http clients? one blocking (ureq) and the other non-blocking (reqwest)

Prior to this PR, `curl` was used. So the PR doesn't _increase_ the number of clients compared to the status quo. Longer-terms, it's probably a good idea to use non-blocking `reqwest` for everything. Would involve a larger refactor of these functions.

**Review by digorithm — APPROVED** [review]
LGTM!

**Review by leviathanbeak — APPROVED** [review]

**Comment by adlerjohn** [comment]
Will wait for @sezna

**Review by sezna — APPROVED** [review]
