### PR TITLE
Fixes type inference on inlined method applications.

### LINKED ISSUE #5802: Compiler fails to recognize type of generic
As the bytes type's `push` function only takes a u8 as an input, that should be enough for the compiler to figure out that try_into should convert the u64 to a u8

Minimum repo

```
library;

#[test]
fn test() {
    use std::bytes::Bytes;
    use std::convert::TryFrom;
    use std::primitive_conversions::u8::*;

    let mut bytes = Bytes::new();
    bytes.push(1_u64.try_into().unwrap());
}
```

Error

```
error
  --> /home/swaystar123/Programming/Sway/tmp/mutvec/src/main.sw:10:22
   |
 8 | 
 9 |     let mut bytes = Bytes::new();
10 |     bytes.push(1_u64.try_into().unwrap());
   |                      ^^^^^^^^ Trait "TryFrom<u64>" is not implemented for type "U".
11 | }
   |
____

error
  --> /home/swaystar123/Programming/Sway/tmp/mutvec/src/main.sw:10:33
   |
 8 | 
 9 |     let mut bytes = Bytes::new();
10 |     bytes.push(1_u64.try_into().unwrap());
   |                                 ^^^^^^ No method named "unwrap" found for type "{unknown}".
11 | }
   |
____

  Aborting due to 2 errors.
Error: Failed to compile mutvec
```

### PR DESCRIPTION
**Pull request by esdrubal**
## Description

We now do the return type unification before doing the second pass of arguments type checking in method application type checking.

Doing the unification sooner fixes the problem we were having while doing:
```
let mut bytes = Bytes::new();
bytes.push(1_u64.try_into().unwrap());
```
With the unification sooner we will unify the return of unwarp with the type annotation of the push argument before we do the type checking of `1_u64.try_into()`. By the time we do `1_u64.try_into()` we will already have the type parameter `U` unified with u8.

Fixes #5802.

## Checklist

- [x] I have linked to any relevant issues.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation where relevant (API docs, the reference, and the Sway book).
   - [ ] If my change requires substantial documentation changes, I have [requested support from the DevRel team](https://github.com/FuelLabs/devrel-requests/issues/new/choose)
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added (or requested a maintainer to add) the necessary `Breaking*` or `New Feature` labels where relevant.
- [x] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [x] I have requested a review from the relevant team or maintainers.

### CODE REVIEW

File: sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs [hunk 1]
```diff
@@ -540,10 +560,109 @@ pub(crate) fn type_check_method_application(
...
+                }
+                let implementing_type_parameters =
+                    implementing_for_typeid.get_type_parameters(type_engine, decl_engine);
+                if let Some(implementing_type_parameters) = implementing_type_parameters {
+                    for p in method.type_parameters.clone() {
+                        if p.is_from_parent {
+                            if let Some(type_param_index) = names_index.get(&p.name_ident) {
+                                if let Some(impl_type_param) =
+                                    implementing_type_parameters.get(*type_param_index)
+                                {
```
Comment (IGI-111) [inline sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs:594]: You can probably use `Option::and_then` to make this not as deep

Comment (IGI-111) [reply sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs:594]: No: 
```suggestion
                            if let Some(impl_type_param) =
                                names_index.get(&p.name_ident).and_then(|type_param_index| {
                                    implementing_type_parameters.get(*type_param_index)
                                })
                            {

```

**Review by IGI-111 — APPROVED** [review]

**Review by xunilrj — APPROVED** [review]
