### PR TITLE
fix: fix formatter adding `--` to multiple `use` statements

### LINKED ISSUE #684: Formatter adding `--` with multi-import statements
Minimal repro:

```rust
script;
use std::chain::{panic, panic};

fn main() {
}
```

Output of `forc fmt --check`:

```diff
script;
-use std::chain::{panic, panic};
+--use std::chain::{panic,panic};

fn main() {
}
```

### PR DESCRIPTION
**Pull request by vnepveu**
This PR fixes #684

### CODE REVIEW

File: sway-fmt/src/fmt.rs [hunk 1]
```diff
@@ -359,7 +359,7 @@ struct Structure {
     name: string, // super comment
 }
 
-struct Structure {
+struct BIMBAMBOUM {
```
Comment (adlerjohn) [inline sway-fmt/src/fmt.rs:362]: Is there a reason for this rename and the one below?

**Review by adlerjohn — COMMENTED** [review]
Could you add a test that shows the behavior is fixed?

**Comment by vnepveu** [comment]
Inadvertently stashed my test… For the rename, it's because of a weird formatter bug, I'm going to explicit it

**Comment by vnepveu** [comment]
Ok implementing the suggested solution. It turns out that the "struct" renaming was indeed linked to 2 blocks of code being identical and a newline appearing because of it.

**Comment by leviathanbeak** [comment]
> It turns out that the "struct" renaming was indeed linked to 2 blocks of code being identical and a newline appearing because of it.

What were the odds lol

File: sway-fmt/src/fmt.rs [hunk 2]
```diff
@@ -641,4 +641,23 @@ fn one_liner() -> bool {
...
+
+    #[test]
+    // This test is here to check that the `use` statements are properly formatted
+    // Currently, there is a hard-to-diagnose bug which adds a leading `--` to the first
+    // `use` statement
+    fn test_use_statement() {
+        let expected_sway = r#"script;
+use std::chain::{panic,log_u8};
+use std::chain::assert;
+use std::address::{Address,Address};
```
Comment (sezna) [inline sway-fmt/src/fmt.rs:653]: Should we import the same thing twice? Isn't that an error?

**Review by sezna — APPROVED** [review]
LGTM but left a question

File: sway-fmt/src/fmt.rs (hunk 2 above)
Comment (vnepveu) [reply sway-fmt/src/fmt.rs:653]: According to https://github.com/FuelLabs/sway/issues/727, it should not compile.

Comment (vnepveu) [reply sway-fmt/src/fmt.rs]: Is it an issue that the formatter didn't raise an error? According to https://fuellabs.github.io/sway/latest/getting-started/temporary_workarounds.html#formatter, we only format compiling code.

File: sway-fmt/src/fmt.rs [hunk 3]
```diff
@@ -341,25 +341,25 @@ struct Rgb {
     blue: u64,
 }
 
-struct Structure {
+struct Bimbam {
```
Comment (leviathanbeak) [inline sway-fmt/src/fmt.rs:344]: these renames are not needed

File: sway-fmt/src/fmt.rs [hunk 4]
```diff
@@ -641,4 +641,23 @@ fn one_liner() -> bool {
         let (_, formatted_code) = result.unwrap();
         assert_eq!(correct_sway_code, formatted_code);
     }
+
+    #[test]
+    // This test is here to check that the `use` statements are properly formatted
+    // Currently, there is a hard-to-diagnose bug which adds a leading `--` to the first
```
Comment (leviathanbeak) [inline sway-fmt/src/fmt.rs:647]: It's actually not hard-to-diagnose, 1st phase of the formatter adds some _metadata_ in the form of patterns like "---", and this bug is introduced since single use-statement is executed 2 or more times after Sway got updated with the ability to import multiple dependencies within a single statement.

File: sway-fmt/src/traversal.rs [hunk 5]
```diff
@@ -69,7 +69,15 @@ fn traverse_ast_node(ast_node: &AstNode, changes: &mut Vec<Change>) {
         }
 
         AstNodeContent::UseStatement(_) => {
-            changes.push(Change::new(&ast_node.span, ChangeType::UseStatement));
+            // The AST generates one root node per use statement, we must avoid duplicating them
+            // while formatting
+            if changes.is_empty() {
```
Comment (leviathanbeak) [inline sway-fmt/src/traversal.rs:74]:
```suggestion
let next_span = &ast_node.span;

            match changes.last() {
                Some(last_change) => {
                    if last_change.start != next_span.start() {
                        changes.push(Change::new(&ast_node.span, ChangeType::UseStatement));
                    }
                }
                _ => changes.push(Change::new(&ast_node.span, ChangeType::UseStatement)),
            }
```

File: sway-fmt/src/fmt.rs (hunk 4 above)
Comment (vnepveu) [reply sway-fmt/src/fmt.rs:647]: Yeah I forgot to remove those, this was during debugging phase

File: sway-fmt/src/fmt.rs (hunk 3 above)
Comment (vnepveu) [reply sway-fmt/src/fmt.rs:344]: forgot to remove aswell after changing the approach

File: sway-fmt/src/fmt.rs [hunk 6]
```diff
@@ -641,4 +641,21 @@ fn one_liner() -> bool {
         let (_, formatted_code) = result.unwrap();
         assert_eq!(correct_sway_code, formatted_code);
     }
+
+    #[test]
+    // Test that the use statements with multiple imports are properly formatted
+    fn test_use_statement() {
+        let expected_sway = r#"script;
+use std::chain::{panic,log_u8};
```
Comment (leviathanbeak) [inline sway-fmt/src/fmt.rs:649]: Although unrelated to this fix, a new issue could be created to actually add space between two imported values.

Current
```
use std::chain::{panic,log_u8};
```
Expected
```
use std::chain::{panic, log_u8};
```

**Review by leviathanbeak — DISMISSED** [review]
👍

File: sway-fmt/src/fmt.rs (hunk 6 above)
Comment (adlerjohn) [reply sway-fmt/src/fmt.rs:649]: Good call. New issue pls (and probably a `good first issue`!).

**Review by adlerjohn — APPROVED** [review]
utACK

**Review by digorithm — DISMISSED** [review]

File: sway-fmt/src/fmt.rs [hunk 7]
```diff
@@ -641,4 +641,21 @@ fn one_liner() -> bool {
...
+use std::chain::assert;
+use std::hash::{HashMethod,hash_value,hash_pair};
```
Comment (mohammadfawaz) [inline sway-fmt/src/fmt.rs:651]: Will you please double check that more complex patterns are also fixed with your change? Example:
```rust
use a::b::{c, d::{e, f}};
use a::b::{c, d::{self, f}};
```

Comment (vnepveu) [reply sway-fmt/src/fmt.rs:651]: Ouch, I can try hahah

File: sway-fmt/src/fmt.rs (hunk 6 above)
Comment (vnepveu) [reply sway-fmt/src/fmt.rs:649]: New issue created!

Comment (adlerjohn) [reply sway-fmt/src/fmt.rs:649]: Ref: #777

**Comment by vnepveu** [comment]
I updated the "Temporary workaround" section about formatting, because, as shown by fe5016ce, we actually *do* format non-compiling code.

**Review by adlerjohn — APPROVED** [review]

**Review by mohammadfawaz — APPROVED** [review]
LGTM! Thanks for adding more test cases.

**Review by digorithm — APPROVED** [review]
