### PR TITLE
Adding `jnzi` to `parse_bytecode` and fixing some notes

### LINKED ISSUE #1650: forc parse-bytecode shows jnzi as undefined
While troubleshooting the contract in this issue: https://github.com/FuelLabs/fuel-vm/issues/126

I attempted to use `forc parse-bytecode`:
```
forc parse-bytecode packages/fuels-abigen-macro/tests/test_projects/revert_transaction_error/out/debug/capture_revert_transaction_error.bin
```

Which printed `Undefined` for the JNZI opcode.

Expected:

```
  half-word   byte   op                raw           notes                           
          0   0      JI(4)             90 00 00 04   conditionally jumps to byte 16  
          ...
          8   32     EQ(16, 17, 16)    13 41 14 00                                   
          9   36     JNZI(16, 11)       73 40 00 0b                                   
         10   40     RVRT(0)           36 00 00 00                                   
         ...
```
Actual
```
  half-word   byte   op                raw           notes                           
          0   0      JI(4)             90 00 00 04   conditionally jumps to byte 16  
          ...
          8   32     EQ(16, 17, 16)    13 41 14 00                                   
          9   36     Undefined         73 40 00 0b                                   
         10   40     RVRT(0)           36 00 00 00                                   
         ...
```

### PR DESCRIPTION
**Pull request by mohammadfawaz**
Closes #1650 

Bumping `fuel-asm` is necessary to get https://github.com/FuelLabs/fuel-asm/pull/66.

Example of what we now see:
```
  half-word   byte   op                raw           notes
          0   0      JI(4)             90 00 00 04   jump to byte 16
          1   4      NOOP              47 00 00 00
          2   8      Undefined         00 00 00 00   data section offset lo (0)
          3   12     Undefined         00 00 00 44   data section offset hi (68)
          4   16     LW(63, 12, 1)     5d fc c0 01
          5   20     ADD(63, 63, 12)   10 ff f3 00
          6   24     LW(16, 63, 0)     5d 43 f0 00
          7   28     JNZI(16, 9)       73 40 00 09   conditionally jump to byte 36
          8   32     JI(13)            90 00 00 0d   jump to byte 52
          9   36     LW(16, 63, 1)     5d 43 f0 01
...
```

### CODE REVIEW

File: forc/src/cli/commands/parse_bytecode.rs [hunk 1]
```diff
@@ -42,8 +42,9 @@ pub(crate) fn exec(command: Command) -> Result<()> {
     for (word_ix, instruction) in instructions.iter().enumerate() {
         use fuel_asm::Opcode::*;
         let notes = match instruction.1 {
-            JI(num) => format!("conditionally jumps to byte {}", num * 4),
-            JNEI(_, _, num) => format!("conditionally jumps to byte {}", num * 4),
+            JI(num) => format!("jump to byte {}", num * 4),
```
Comment (otrho) [inline forc/src/cli/commands/parse_bytecode.rs:45]: Yay. :smile:

**Review by otrho — APPROVED** [review]
