### PR TITLE
Remove `MOVE $$locbase, $$sp` if non-entry function doesn't use stack

### LINKED ISSUE #7547: Register pressure makes compiler panic in `register_allocator::spill`
E.g., compiling this code:

```
script;

#[inline(never)]
fn dummy() -> u64 {
    42
}

#[inline(never)]
fn reg_pressure() -> u64 {
    let v01: u64 = dummy();
    let v02: u64 = dummy();
    let v03: u64 = dummy();
    let v04: u64 = dummy();
    let v05: u64 = dummy();
    let v06: u64 = dummy();
    let v07: u64 = dummy();
    let v08: u64 = dummy();
    let v09: u64 = dummy();
    let v10: u64 = dummy();
    let v11: u64 = dummy();
    let v12: u64 = dummy();
    let v13: u64 = dummy();
    let v14: u64 = dummy();
    let v15: u64 = dummy();
    let v16: u64 = dummy();
    let v17: u64 = dummy();
    let v18: u64 = dummy();
    let v19: u64 = dummy();
    let v20: u64 = dummy();
    let v21: u64 = dummy();
    let v22: u64 = dummy();
    let v23: u64 = dummy();
    let v24: u64 = dummy();
    let v25: u64 = dummy();
    let v26: u64 = dummy();
    let v27: u64 = dummy();
    let v28: u64 = dummy();
    let v29: u64 = dummy();
    let v30: u64 = dummy();
    let v31: u64 = dummy();
    let v32: u64 = dummy();
    let v33: u64 = dummy();
    let v34: u64 = dummy();
    let v35: u64 = dummy();
    let v36: u64 = dummy();
    let v37: u64 = dummy();
    let v38: u64 = dummy();
    let v39: u64 = dummy();
    let v40: u64 = dummy();
    let v41: u64 = dummy();
    let v42: u64 = dummy();
    let v43: u64 = dummy();
    let v44: u64 = dummy();
    let v45: u64 = dummy();
    let v46: u64 = dummy();
    let v47: u64 = dummy();
    let v48: u64 = dummy();
    let v49: u64 = dummy();
    let v50: u64 = dummy();
    let v51: u64 = dummy();
    let v52: u64 = dummy();
    let v53: u64 = dummy();
    let v54: u64 = dummy();
    let v55: u64 = dummy();
    let v56: u64 = dummy();
    let v57: u64 = dummy();
    let v58: u64 = dummy();
    let v59: u64 = dummy();
    let v60: u64 = dummy();
    let v61: u64 = dummy();
    let v62: u64 = dummy();
    let v63: u64 = dummy();
    let v64: u64 = dummy();

    v01 + v02 + v03 + v04 + v05 + v06 + v07 + v08 + v09 + v10 + v11 + v12
        + v13 + v14 + v15 + v16 + v17 + v18 + v19 + v20 + v21 + v22 + v23
        + v24 + v25 + v26 + v27 + v28 + v29 + v30 + v31 + v32 + v33 + v34
        + v35 + v36 + v37 + v38 + v39 + v40 + v41 + v42 + v43 + v44 + v45
        + v46 + v47 + v48 + v49 + v50 + v51 + v52 + v53 + v54 + v55 + v56
        + v57 + v58 + v59 + v60 + v61 + v62 + v63 + v64
}

fn main(a: u64) -> u64 {
    reg_pressure()
}
```

results in:

```
thread 'main' panicked at sway-core/src/asm_generation/fuel/register_allocator.rs:742:31:
Function does not have CFEI instruction for locals
```

### PR DESCRIPTION
**Pull request by ironcev**
## Description

This PR:
- removes redundant `MOVE $$locbase, $$sp` if non-entry function doesn't use stack at all.
- fixes #7547

If the function does not use stack at all, the $$locbase is never used, by definition.

Not using stack at all means that the function:
- does not have any locals
- does not call any functions that spill arguments to the stack
- does not spill any registers to the stack when allocating registers

Having `MOVE $$locbase, $$sp` *in entry functions* is a part of compiler's contract and tooling relies on it. Therefore, `MOVE $$locbase, $$sp` remains in entry functions even if `$$locbase` is not used.

On the contrary, in non-entry functions, setting `$$locbase` is an implementation detail no tooling relies on. E.g. a `forc debug` or similar.

Additionally, the PR:
- groups function prologue and epilogue instructions into `[fn/entry init/end]` groups for better readability and easier analysis of ASM. Also, it opens the way towards better automatic analysis of ASM output if needed in the future.
- adapts `filter-fn` to use the new `[fn/entry init/end: <fn name>]`comments.

- Fixes #7547.

## Checklist

- [x] I have linked to any relevant issues.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation where relevant (API docs, the reference, and the Sway book).
   - [ ] If my change requires substantial documentation changes, I have [requested support from the DevRel team](https://github.com/FuelLabs/devrel-requests/issues/new/choose)
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added (or requested a maintainer to add) the necessary `Breaking*` or `New Feature` labels where relevant.
- [x] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [x] I have requested a review from the relevant team or maintainers.

### CODE REVIEW

**Comment by ironcev** [comment]
:+1:

**Comment by ironcev** [comment]
Comparing 'e2e-gas-usages':

|   | Improvements | Regressions |
| - | -: | -: |
| Count   | 268 | — |
| Average | 1.65% | — |
| Median  | 1.61% | — |
| Max     | 8.22% | — |
| Min     | 0.01% | — |

Comparing 'e2e-bytecode-sizes':

|   | Improvements | Regressions |
| - | -: | -: |
| Count   | 188 | — |
| Average | 5.09% | — |
| Median  | 2.86% | — |
| Max     | 12.50% | — |
| Min     | 0.03% | — |

Comparing 'in-language-gas-usages':

|   | Improvements | Regressions |
| - | -: | -: |
| Count   | 418 | — |
| Average | 1.43% | — |
| Median  | 1.37% | — |
| Max     | 4.44% | — |
| Min     | 0.01% | — |

Comparing 'bytecode-sizes' for project 'o2':

|   | Improvements | Regressions |
| - | -: | -: |
| Count   | 12 | — |
| Average | 0.14% | — |
| Median  | 0.12% | — |
| Max     | 0.21% | — |
| Min     | 0.09% | — |

Comparing 'gas-usages' for project 'o2':

|   | Improvements | Regressions |
| - | -: | -: |
| Count   | 65 | — |
| Average | 0.06% | — |
| Median  | 0.04% | — |
| Max     | 1.69% | — |
| Min     | 0.02% | — |

File: sway-core/src/asm_generation/fuel/functions.rs [hunk 1]
```diff
@@ -1045,7 +1058,7 @@ impl FuelAsmBuilder<'_, '_> {
             opcode: Either::Left(
                 VirtualOp::CFSI(VirtualRegister::Constant(ConstantRegister::StackPointer),
                 VirtualImmediate24::new(locals_size_bytes + (max_num_extra_args * 8), ))),
-            comment: format!("free {locals_size_bytes} bytes for locals and {max_num_extra_args} slots for extra call arguments"),
+            comment: format!("[{} end: {fn_name}] free: locals {locals_size_bytes} byte(s), call args {max_num_extra_args} slot(s)", if is_entry_fn { "entry" } else { "fn" }),
```
[the remark this answers is not in the document]
Comment (ironcev) [reply sway-core/src/asm_generation/fuel/functions.rs]: Good point! Solved!

File: sway-core/src/asm_generation/fuel/optimizations/misc.rs [hunk 2]
```diff
@@ -101,9 +101,6 @@ impl AbstractInstructionSet {
             let remove = match &op.opcode {
                 Either::Left(VirtualOp::NOOP) => true,
                 Either::Left(VirtualOp::MOVE(a, b)) => a == b,
-                Either::Left(VirtualOp::CFEI(_, imm)) | Either::Left(VirtualOp::CFSI(_, imm)) => {
```
Comment (xunilrj) [inline sway-core/src/asm_generation/fuel/optimizations/misc.rs:104]: Why are we not removing them anymore? Even if we are not generating them anymore, I would leave this here to be future-proof.

File: sway-core/src/asm_generation/fuel/programs/abstract.rs [hunk 3]
```diff
@@ -136,10 +136,15 @@ impl AbstractProgram {
             .collect::<Result<Vec<AllocatedAbstractInstructionSet>, CompileError>>()?;
 
         // Optimize allocated functions.
-        // TODO: Add verification. E.g., verify that the stack use for each function is balanced.
         let functions = allocated_functions
             .into_iter()
             .map(|instruction_set| instruction_set.optimize())
+            // TODO: Add verification. E.g., verify that:
```
Comment (xunilrj) [inline sway-core/src/asm_generation/fuel/programs/abstract.rs:142]: Not for this PR? Better to crate a github issue

File: sway-core/src/asm_generation/fuel/optimizations/misc.rs (hunk 2 above)
Comment (ironcev) [reply sway-core/src/asm_generation/fuel/optimizations/misc.rs:104]: Ha ha, in the first commit I [actually had this warning](https://github.com/FuelLabs/sway/pull/7548/changes/02730741f76a86bb69a9f9ebef48bd9eb7c2e189#diff-7f42d9782441c70b3945d25936f7d678f22033271a64415a12ee8f63763cdcbfR104):

```
// Note that we **must not** remove CFEI/CFSI with an immediate of 0,
// as they are used later on. E.g., in case of spilling when allocating registers.
```

Then after adding the test that checks #7547 is fixed, I've removed the warning. They are removed later on when optimizing allocated inst set.

I'll put the comment back, but let's do that in the PR which verifies the final set.

File: sway-core/src/asm_generation/fuel/programs/abstract.rs (hunk 3 above)
Comment (ironcev) [reply sway-core/src/asm_generation/fuel/programs/abstract.rs:142]: Done: https://github.com/FuelLabs/sway/issues/7553
