### PR TITLE
Don't duplicate source pointers in spans

### LINKED ISSUE #7338: contract tests can create incompatible spans
The following source:
```sway
contract;

struct Fleet {
    id: b256, // id of the fleet
}

#[test]
fn can_commit_and_reveal() {
    let _ = Fleet {
    };
}
```
panics when running `forc test` with:
```
thread 'main' panicked at sway-types/src/span.rs:279:9:
Spans from different files cannot be joined.
```

Due to this assert in `sway-types/src/span.rs`:
```rust
        assert!(
            Arc::ptr_eq(&s1.src.text, &s2.src.text) && s1.source_id == s2.source_id,
            "Spans from different files cannot be joined.",
        );
```
specifically because the text pointers are not equal. The source ids are actually the same.

Changing this from a `contract` to a `script` no longer panics and instead produces the following correct error:

```
error: Struct instantiation has missing fields
  --> /home/igi-111/Code/scratch/src/main.sw:9:13
   |
...   |
 5 |  | }
   |  |_- info: Struct "Fleet" is declared here, and has one field.
...
 9 |        let _ = Fleet {
   |   _____________^
   |   _____________-
10 |  |     };
   | ||_____^ Instantiation of the struct "Fleet" is missing the field "id".
   |  |_____- help: Struct instantiation must initialize all the fields of the struct.
   |
```

### PR DESCRIPTION
**Pull request by IGI-111**
## Description

When doing multiple subsequent compilations, such as when running tests or when using the LSP, and reusing engines, in particular the decl engine, an condition can occur when files are loaded a second time and generate new spans that point to a different string than existing spans for that file.

This creates a problem when joining spans that point to the same source file but not the same string.

This PR adds a new functionality to the source engine, where it will store pointers to source strings (that spans eventually use) and deduplicate them before they can cause this issue.

A future PR may want to reuse this facility to prevent unnecessary file loads altogether.

Fixes #7338

## Checklist

- [ ] I have linked to any relevant issues.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation where relevant (API docs, the reference, and the Sway book).
   - [ ] If my change requires substantial documentation changes, I have [requested support from the DevRel team](https://github.com/FuelLabs/devrel-requests/issues/new/choose)
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added (or requested a maintainer to add) the necessary `Breaking*` or `New Feature` labels where relevant.
- [ ] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [ ] I have requested a review from the relevant team or maintainers.

### CODE REVIEW

File: sway-types/src/source_engine.rs [hunk 1]
```diff
@@ -62,6 +64,20 @@ impl SourceEngine {
...
+        source_id: &SourceId,
+        source: span::Source,
+    ) -> span::Source {
+        let mut map = self.source_to_buffer_map.write();
+        if !map.contains_key(source_id) {
+            map.insert(*source_id, source.clone());
+            source
+        } else {
+            map.get(source_id).unwrap().clone()
+        }
```
Comment (ironcev) [inline sway-types/src/source_engine.rs]: Using `entry` will give idiomatic code with clear intent. Something along:

```rust
map.entry(source_id).or_insert_with(|| source.clone()).clone();
```

**Review by ironcev — APPROVED** [review]
