### PR TITLE
Check for storage types in impl method params

### LINKED ISSUE #4040: `StorageVec` not disallowed as argument to methods and trait declarations.
Normally, when trying to pass a struct like `StorageVec` to a public function we expect an error informing the user that it may only be declared as a storage field. An example function of this works properly is:

```rust
#[storage(read, write)]
pub fn takes_storage_struct(my_struct: StorageVec<u64>) {
    my_struct.push(5);
}
```
The code above produces the following error:
`Type StorageVec<u64> can only be declared directly as a storage field`

However, if attempting to do the same in an impl block for another struct and passing `self` as an argument, we get an internal compiler error. For example:

```rust
pub struct MyStruct {}

impl MyStruct {
    #[storage(read, write)]
    pub fn takes_storage_struct(self, my_struct: StorageVec<u64>) {
        my_struct.push(5);
    }
}
```
This code above produces the following internal compiler error:
internal_compiler_error

It should be noted that removing the `self` argument of `takes_storage_struct` will not produce any errors and compile. For example:

```rust pub struct MyStruct {}

impl MyStruct {
    #[storage(read, write)]
    pub fn takes_storage_struct(my_struct: StorageVec<u64>) {
        my_struct.push(5);
    }
}
```

This was tested on forc v0.35.0

### PR DESCRIPTION
**Pull request by vaivaswatha**
## Description
Fixes #4040 

There is an exception for `self` parameters, to avoid the error being thrown for impl of the actual storage types (in storage.sw). I'm not sure if that's the best way to add that exception. Reviewers please advice. [Edit: This is fixed, thanks @anton-trunov ]

## Checklist

- [x] I have linked to any relevant issues.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation where relevant (API docs, the reference, and the Sway book).
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added (or requested a maintainer to add) the necessary `Breaking*` or `New Feature` labels where relevant.
- [x] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [x] I have requested a review from the relevant team or maintainers.

### CODE REVIEW

File: sway-core/src/semantic_analysis/storage_only_types.rs [hunk 1]
```diff
@@ -267,6 +267,21 @@ fn decl_validate(engines: Engines<'_>, decl: &ty::TyDeclaration) -> CompileResul
                             warnings,
                             errors
                         );
+                        for param in method.parameters {
+                            if param.name.as_str() != "self" {
```
Comment (anton-trunov) [inline sway-core/src/semantic_analysis/storage_only_types.rs:271]: Maybe something like this?

```suggestion
                            if !param.is_self() {
```

Comment (vaivaswatha) [reply sway-core/src/semantic_analysis/storage_only_types.rs:271]: Thanks @anton-trunov , that works. I didn't know that the method existed.

**Review by mohammadfawaz — APPROVED** [review]
Thanks!

**Review by anton-trunov — APPROVED** [review]
