### PR TITLE
Fix comments preceding `module_kind`

### LINKED ISSUE #2739: Fix (and then run) `forc fmt` for `sway-lib-core` and `sway-lib-std`
1. Running `forc fmt` on `sway-lib-core` leads to the following error:
```console
❯ forc fmt

This file: "/Users/mohammad/Desktop/fuel/sway/sway-lib-core/src/ops.sw" is not part of the build
Error parsing file: Unable to parse: Expected `fn`.
```

2. Running `forc fmt` on `sway-lib-std` leads to the following error:
```console
❯ forc fmt

This file: "/Users/mohammad/Desktop/fuel/sway/sway-lib-std/src/reentrancy.sw" is not part of the build
Error parsing file: Unable to parse: Expected a module kind (script, contract, predicate or library).


This file: "/Users/mohammad/Desktop/fuel/sway/sway-lib-std/src/option.sw" is not part of the build
Error parsing file: Unable to parse: Expected a module kind (script, contract, predicate or library).


This file: "/Users/mohammad/Desktop/fuel/sway/sway-lib-std/src/inputs.sw" is not part of the build
Error parsing file: Unable to parse: Expected a module kind (script, contract, predicate or library).


This file: "/Users/mohammad/Desktop/fuel/sway/sway-lib-std/src/hash.sw" is not part of the build
Error parsing file: Unable to parse: Unexpected token after asm return type.


This file: "/Users/mohammad/Desktop/fuel/sway/sway-lib-std/src/result.sw" is not part of the build
Error parsing file: Unable to parse: Expected a module kind (script, contract, predicate or library).


This file: "/Users/mohammad/Desktop/fuel/sway/sway-lib-std/src/alloc.sw" is not part of the build
Error parsing file: Unable to parse: Expected a module kind (script, contract, predicate or library).


This file: "/Users/mohammad/Desktop/fuel/sway/sway-lib-std/src/outputs.sw" is not part of the build
Error parsing file: Unable to parse: Expected a module kind (script, contract, predicate or library).


This file: "/Users/mohammad/Desktop/fuel/sway/sway-lib-std/src/context/registers.sw" is not part of the build
Error parsing file: Unable to parse: Expected a module kind (script, contract, predicate or library).


This file: "/Users/mohammad/Desktop/fuel/sway/sway-lib-std/src/context/call_frames.sw" is not part of the build
Error parsing file: Unable to parse: Expected a module kind (script, contract, predicate or library).
```
Some of these errors go away if I remove the first few lines of comments at the start of the library file (such as `option.sw).

### PR DESCRIPTION
**Pull request by eureka-cpu**
Closes #2739

also ref #2649 though I don't believe this PR will close it, they are similar issues

### CODE REVIEW

File: swayfmt/src/utils/map/comments.rs [hunk 1]
```diff
@@ -232,15 +232,22 @@ fn insert_after_span(
     let iter = comments_to_insert.iter();
     let mut offset = offset;
     let mut comment_str = String::new();
+    let mut pre_module_comment = false;
     for comment_with_context in iter {
         let (comment_value, comment_context) = comment_with_context;
+        if comment_value.span.start() == 0 {
```
Comment (mitchmindtree) [inline swayfmt/src/utils/map/comments.rs:238]: I wonder if this condition should be:

```suggestion
        if comment_value.span.start() < from.start() {
```

Though I'm not sure exactly what the `from` span represents here - is it the span of the current item being checked for comments?

---

The issue that comes to mind with using `0` is that this might not work in the case that there's some empty whitespace at the top of the file, e.g.

```rust
 
// Blah blah
library foo;
```
Arguably, there shouldn't be any unnecessary leading whitespace at the top of the file, though we can't be sure the user won't run the formatter with an extra newline at the top.

One potentially hacky solution might be to always `.trim()` the unformatted code `str` before we begin any formatting or parsing to make sure there's no empty whitespace at the beginning or end of the `str`. I think in that case, the comparison to `== 0` here should be OK as if there is a comment preceding the module kind, it would always start at `0`. We might want to add a test to check the case of having an extra newline before the first comment just in case.

**Review by mitchmindtree — APPROVED** [review]
I've left a comment at one potentially problematic spot, however I'm happy to approve either way if this improves the majority of troublesome cases in the meantime.

File: swayfmt/src/utils/map/comments.rs (hunk 1 above)
Comment (eureka-cpu) [reply swayfmt/src/utils/map/comments.rs:238]: This is actually something I was thinking as well, though in a slightly different context. The comments I think should never have a preceding new line, all new lines should be handled in `newline_handling` including ones that are on comments.

Comment (eureka-cpu) [reply swayfmt/src/utils/map/comments.rs:238]: #2790

**Review by JoshuaBatty — APPROVED** [review]
