### PR TITLE
fix: formatting for loop

### LINKED ISSUE #6804: Formatter fails when formatting with `for` loop
When a contract contains a `for` loop, the formatter will fail.

Example:
```sway
contract;

abi MyContract {
    fn test_function() -> bool;
}

impl MyContract for Contract {
    fn test_function() -> bool {
        let mut my_vec: Vec<u64> = Vec::new();
        for iter in my_vec.iter() {

        }

        true
    }
}
```

Screenshot 2025-01-03 at 17 54 23

### PR DESCRIPTION
**Pull request by amiremohamadi**
## Description
Fix #6804

## Checklist

- [x] I have linked to any relevant issues.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation where relevant (API docs, the reference, and the Sway book).
   - [ ] If my change requires substantial documentation changes, I have [requested support from the DevRel team](https://github.com/FuelLabs/devrel-requests/issues/new/choose)
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added (or requested a maintainer to add) the necessary `Breaking*` or `New Feature` labels where relevant.
- [ ] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [ ] I have requested a review from the relevant team or maintainers.

### CODE REVIEW

File: swayfmt/src/utils/language/expr/mod.rs [hunk 1]
```diff
@@ -282,6 +282,7 @@ impl Format for Expr {
                     |formatter| -> Result<(), FormatterError> {
                         write!(formatted_code, "{} ", for_token.span().as_str())?;
                         value_pattern.format(formatted_code, formatter)?;
+                        write!(formatted_code, " ")?;
                         write!(formatted_code, "{} ", in_token.span().as_str())?;
```
Comment (IGI-111) [inline swayfmt/src/utils/language/expr/mod.rs:286]: Sure this can be this:
```suggestion
                        write!(formatted_code, " {} ", in_token.span().as_str())?;
```

**Review by zees-dev — APPROVED** [review]
Nice; tested and seems to be working 👍

**Review by JoshuaBatty — CHANGES_REQUESTED** [review]
This doesn't solve the issue. 

There is already white space added after the `for` keyword so this change just pads more white space. 

Locking this while I look into it.

**Comment by zees-dev** [comment]
> This doesn't solve the issue.
> 
> There is already white space added after the `for` keyword so this change just pads more white space.
> 
> Locking this while I look into it.

I manually tested switching to the PR branch to validate.
Weird, there maybe a deeper underlying issue then; thanks for looking deeper!

**Comment by JoshuaBatty** [comment]
This looks like a parser error. If we take the example for from the linked issue and run it we get a parser error. @IGI-111 any idea why the parser would be failing here?

```rust

#[test]
fn contract_for_loop() {
    check(
        indoc! {r#"
        contract;

        abi MyContract {
            fn test_function() -> bool;
        }

        impl MyContract for Contract {
            fn test_function() -> bool {
                let mut my_vec: Vec<u64> = Vec::new();
                for iter in my_vec.iter() {

                }

                true
            }
        }
        "#},
        indoc! {r#"
        contract;

        abi MyContract {
            fn test_function() -> bool;
        }

        impl MyContract for Contract {
            fn test_function() -> bool {
                let mut my_vec: Vec<u64> = Vec::new();
                for iter in my_vec.iter() {

                }

                true
            }
        }
        "#},
    );
}
```
thread 'contract_for_loop' panicked at swayfmt/tests/mod.rs:9:86:
called `Result::unwrap()` on an `Err` value: ParseFileError(ParseFileError([Parse { error: ParseError { span: Span { src (ptr): 0x149a04180, source_id: None, start: 95, end: 101, as_str(): "my_vec" }, kind: ExpectedKeyword { word: "in" } } }]))
```

**Comment by amiremohamadi** [comment]
@JoshuaBatty thanks for the review! The issue isn't with adding a space after the `for` keyword, but rather with `AmbiguousSingleIdent`. In this case, it treats

```rust
for iter in my_vec.iter() {
}
```

as if it was written like:

```rust
for iterin my_vec.iter() {
}
```

**Comment by IGI-111** [comment]
Fixing the `in` keyword handling seems to do the trick, but @amiremohamadi can you add a test that validates the example from the issue that Josh is quoting here?

**Comment by kayagokalp** [comment]
Seems like we have couple conflicts @amiremohamadi before we can continue running the CI

**Comment by amiremohamadi** [comment]
@kayagokalp rebased my changes

**Review by alfiedotwtf — APPROVED** [review]

**Review by IGI-111 — APPROVED** [review]

**Review by JoshuaBatty — APPROVED** [review]
