### PR TITLE
fix: prevent duplicate sway unit test execution

### LINKED ISSUE #3813: Sway unit tests are run multiple times
In my current project, some(but not all) of the unit tests run twice.
One thing to note with my project (a library) is that the tests are currently spread across multiple files/libraries.
I haven't managed to create a minimal repro yet, but here is a link to my branch: https://github.com/FuelLabs/sway-applications/tree/furnic/add-abi-and-contract/chess-game 

Here is a sample of the output. Note that there are actually only 5 unique tests being run here:
```
Bytecode size is 1700 bytes.
   Running 16 tests

   tested -- lib_chess

      test test_new_bitstack ... ok (229µs)
      test test_new_bitstack ... ok (99.875µs)
      test test_to_u8 ... ok (321.125µs)
      test test_to_u8 ... ok (321.25µs)
      test test_multimask ... ok (2.139291ms)
      test test_new_board ... ok (164.291µs)
      test test_increment_half_move_counter ... ok (211.958µs)
      test test_to_u8 ... ok (352.75µs)
      test test_new_bitstack ... ok (215.166µs)
      test test_to_u8 ... ok (347.708µs)
      test test_to_u8 ... ok (338µs)
      test test_multimask ... ok (2.069458ms)
      test test_new_board ... ok (138.083µs)
      test test_increment_half_move_counter ... ok (156.333µs)
      test test_to_u8 ... ok (312.375µs)
      test test_to_u8 ... ok (310.208µs)
   Result: OK. 16 passed. 0 failed. Finished in 7.726871ms.
```

 cc @kayagokalp

### PR DESCRIPTION
**Pull request by kayagokalp**
## Description
This PR adds a step to execution of unit tests so that duplicate unit tests are omitted. Duplicate tests are generated from dependencies declared with `dep` keyword in a duplicate manner (see #3947). Until that is fixed this PR de-duplicates sway unit tests based on their `span`. Once the fix for #3947 is ready we can remove the changes from this PR. This is also commented in the code.

closes #3813.

## Checklist

- [x] I have linked to any relevant issues.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation where relevant (API docs, the reference, and the Sway book).
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added (or requested a maintainer to add) the necessary `Breaking*` or `New Feature` labels where relevant.
- [x] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [x] I have requested a review from the relevant team or maintainers.

### CODE REVIEW

**Review by mohammadfawaz — APPROVED** [review]

File: forc-test/src/lib.rs [hunk 1]
```diff
@@ -189,12 +190,15 @@ impl<'a> PackageTests {
 
     /// Run all tests for this package and collect their results.
     pub(crate) fn run_tests(&self) -> anyhow::Result<TestedPackage> {
+        // TODO: Remove this once https://github.com/FuelLabs/sway/issues/3947 is solved.
```
Comment (JoshuaBatty) [inline forc-test/src/lib.rs:193]: Can you open an issue linking to #3947 as a reminder to remove these changes after that lands?

**Review by JoshuaBatty — APPROVED** [review]

File: forc-test/src/lib.rs (hunk 1 above)
Comment (kayagokalp) [reply forc-test/src/lib.rs:193]: Good idea!
