### PR TITLE
Prevent an illegal use of a generic from crashing the compiler

### LINKED ISSUE #3270: Illegal use of a generic crashes compiler
As a victim of "Find and Replace", I have stumbled upon a case that crashes the compiler.

The illegal use of trying to call a function from a generic such as `new()`  will make the compiler panic:

```
    fn test_function(self, value: T) {
        T::new();
    }
```
illegal_use_of_generic

### PR DESCRIPTION
**Pull request by emilyaherbert**
This PR removes an `unreachable!` that we had inside one of the impl blocks for `Spanned`.

In implementing this PR, I noticed that we hadn't been using `ty::TyDeclaration::ErrorRecovery` anywhere! Rather than remove it, I've inserted places where we now use it, to hopefully remove some cascading errors.

Closes #3270

### CODE REVIEW

**Review by mohammadfawaz — APPROVED** [review]
Seems reasonable. Thanks!.

Question: what is the reason for changing `nextln` to `check` the `test.toml` files you've updated?

**Comment by emilyaherbert** [comment]
> Question: what is the reason for changing `nextln` to `check` the `test.toml` files you've updated?

The `nextln:` directive appears to have some whitespace sensitivity issues that were causing it to fail with the updated errors being reported. https://github.com/bytecodealliance/filecheck/issues/2

File: sway-core/src/semantic_analysis/ast_node/declaration/mod.rs [hunk 1]
```diff
@@ -1,4 +1,6 @@
 mod abi;
+#[allow(clippy::module_inception)]
+mod declaration;
```
Comment (otrho) [inline sway-core/src/semantic_analysis/ast_node/declaration/mod.rs:3]: In the source on my machine this is still in `ast_node/declaration.rs` and it seems like the new `declaration.rs` code taken from `ast_node/mod.rs` could go in there or here in this `mod.rs` since it's so small and the module inception could be avoided.

**Review by otrho — APPROVED** [review]
Nit on the code reorg, but cool otherwise.
