### PR TITLE
Parse document for tokens on every LSP on_change event

### LINKED ISSUE #1147: Token length param isn't being updated on Symbol rename
When renaming a symbol in the language server, the initial length of the token is left unchanged leading to incorrect highlighting.

### LINKED ISSUE #1177: Parse document and publish Diagnostics after each did_change event
Currently, we are only parsing the document on the `did_open` and `did_save` events in the LSP server. Internally, these events are parsing the entire open document and then publishing diagnostics back to VScode. 

When parsing happens, the `Vec` and `HashMap`s that store the documents tokens are populated. We use these for doing things like goto, rename, hover etc.. 

### Problem:
At the moment, when the server receives a `did_change` event, we modify the internal document in memory with just the changes reported by the client. However, we don't update the documents internal `HashMap`s or `Vec` of tokens to reflect this, nor do we report any diagnostics. 

### Proposition:
Considering we most likely aren't likely to see multi-thousand line sway files, perhaps we could just reparse the entire document on every change. This would allow for an easy way to ensure everything stays in sync, and give users real-time diagnostics feedback for any errors or warnings that were detected. It would also mean issues like #1147 would be eliminated from happening. 

I have seen a few LSP server implementation examples that seem to be taking this approach. Perhaps we could adopt re-parsing the document on every change for now as a quick win, and only look to optimize if we notice any performance issues? 

any thoughts @adlerjohn @mitchmindtree @leviathanbeak ?

### PR DESCRIPTION
**Pull request by JoshuaBatty**
see #1177 for context. 

closes #1177 and closes #1147

### CODE REVIEW

File: sway-lsp/src/capabilities/text_sync.rs [hunk 1]
```diff
@@ -21,35 +21,31 @@ pub fn handle_open_file(
...
 }
 
 pub fn handle_change_file(
     session: Arc<Session>,
     params: DidChangeTextDocumentParams,
-) -> Result<(), DocumentError> {
-    session.update_text_document(&params.text_document.uri, params.content_changes)
+) -> Vec<Diagnostic> {
+    let path = params.text_document.uri.path();
+    let _ = session.update_text_document(&params.text_document.uri, params.content_changes);
```
Comment (mitchmindtree) [inline sway-lsp/src/capabilities/text_sync.rs:32]: Looks like a `Result` might be getting ignored here now?

Perhaps the return type of this method should be:

```rust
-> Result<Vec<Diagnostic>, DocumentError>
```

And this line should be:

```rust
session.update_text_document(&params.text_document.uri, params.content_changes)?;
```

Otherwise if there's a reason it's ignored, we should add a comment to justify it.

**Review by mitchmindtree — CHANGES_REQUESTED** [review]

File: sway-lsp/src/capabilities/text_sync.rs (hunk 1 above)
Comment (JoshuaBatty) [reply sway-lsp/src/capabilities/text_sync.rs:32]: That's a fair point. The original possible error comes from using the path as the key into a HashMap of files, if the key doesn't exist an error is returned. The error is being ignored because we never want our server to crash. There is probably no point in returning an error at all then from the `update_text_document` fn. I'll update that fn now.

File: sway-lsp/src/core/session.rs [hunk 2]
```diff
@@ -63,19 +63,11 @@ impl Session {
...
-                    document.apply_change(change);
-                });
-                Ok(())
-            }
-            _ => Err(DocumentError::DocumentNotFound),
+    pub fn update_text_document(&self, url: &Url, changes: Vec<TextDocumentContentChangeEvent>) {
+        if let Some(ref mut document) = self.documents.get_mut(url.path()) {
+            changes.iter().for_each(|change| {
+                document.apply_change(change);
+            });
```
Comment (mitchmindtree) [inline sway-lsp/src/core/session.rs:70]: I guess once we get some logging we could do something like `log::warn!("no document for url: {}", url);` or something along those lines.

**Review by mitchmindtree — APPROVED** [review]
Nice one chap, I think this approach makes a lot of sense at least until we notice re-parsing the whole document causing performance issues downstream!

When/if we do re-visit manually updating small sections of a doc for optimisation purposes, we might want to do so alongside a discussion around incremental parsing in `sway-core` itself.

File: sway-lsp/src/core/session.rs (hunk 2 above)
Comment (JoshuaBatty) [reply sway-lsp/src/core/session.rs:70]: Yeah exactly, logging warnings to the console makes more sense to report errors than crashing for an LSP server.

**Comment by JoshuaBatty** [comment]
> When/if we do re-visit manually updating small sections of a doc for optimisation purposes, we might want to do so alongside a discussion around incremental parsing in sway-core itself.

Yeah exactly, makes a lot of sense for the functionality to come from `sway-core`. Everything still feels pretty snappy on my end for now anyway.
