### PR TITLE
Fix E2E tests for IR.

### LINKED ISSUE #709: `retd_struct` E2E test is currently failing with IR pipeline.

### PR DESCRIPTION
**Pull request by otrho**
These are some relatively minor fixes for bugs which accrued while I was away.  The E2E tests were failing sometimes when using IR, these changes fix that.

The `ec_recover_test` still fails with IR but will be resolved when the new `B512` code in `sway-lib-std` is released.

Closes #709

### CODE REVIEW

File: test/src/e2e_vm_tests/mod.rs [hunk 1]
```diff
@@ -53,27 +52,24 @@ pub fn run(filter_regex: Option<regex::Regex>) {
...
-        // TEMPORARILY DISABLED DUE TO OOM ("const_decl_in_library", ProgramState::Return(1)), // true
+        ("const_decl_in_library", ProgramState::Return(1)), // true
         ("aliased_imports", ProgramState::Return(42)),
         ("empty_method_initializer", ProgramState::Return(1)), // true
         ("b512_struct_alignment", ProgramState::Return(1)),    // true
         ("generic_structs", ProgramState::Return(1)),          // true
         ("generic_functions", ProgramState::Return(1)),        // true
         ("generic_enum", ProgramState::Return(1)),             // true
         ("import_method_from_other_file", ProgramState::Return(10)), // true
-        ("b512_test", ProgramState::Return(1)),                // true
```
Comment (sezna) [inline test/src/e2e_vm_tests/mod.rs:64]: would you rather comment these out instead of deleting them so they aren't forgotten?

**Comment by nfurfaro** [comment]
A new version of `sway-lib-std` was released so that should help with failing tests here.

File: test/src/e2e_vm_tests/mod.rs (hunk 1 above)
Comment (otrho) [reply test/src/e2e_vm_tests/mod.rs:64]: They were all duplicates.

**Review by sezna — APPROVED** [review]
