### PR TITLE
Fix Project Manifest File Names

### LINKED ISSUE #763: Using `forc init directory/project` creates a project with name `directory/project`
While the command successfully creates the project at the `directory/project` location, it also uses the full path as a name in the `Forc.toml` manifest. This also results in an error the first time a user attempts to run `forc build` as `directory/project` is an invalid project name due to the use of the `/` character.

I think the behaviour we really want is for the final name in the given path to be used as the project name.

### PR DESCRIPTION
**Pull request by ControlCplusControlV**
Fixes #763 , pretty simple name split as a string, still new to Rust though so lmk if you run into any formatting issues or similar, but otherwise this fix is pretty self explanatory

### CODE REVIEW

File: forc/src/ops/forc_init.rs [hunk 1]
```diff
@@ -4,6 +4,8 @@ use std::fs;
 use sway_utils::constants;
 
 pub(crate) fn init_new_project(project_name: String) -> Result<()> {
+    let neat_name:String = project_name.split("/").last().unwrap().to_string();
+
     // Make a new directory for the project
     fs::create_dir_all(format!("{}/src", project_name))?;
```
Comment (mitchmindtree) [inline forc/src/ops/forc_init.rs:10]: Ahh unrelated to this PR, but we shouldn't be using `format!` to create paths like this as it breaks Windows support. I'll open a separate issue for this so we can address it in a future PR.

**Review by mitchmindtree — COMMENTED** [review]
Looks like you might need to run `cargo fmt`, otherwise LGTM!

File: forc/src/ops/forc_init.rs (hunk 1 above)
Comment (ControlCplusControlV) [reply forc/src/ops/forc_init.rs:10]: Yeah I was contemplating using Path from the Rust standard library but that seems like another refactor in itself

**Comment by ControlCplusControlV** [comment]
@mitchmindtree Should be formatted now!

File: forc/src/ops/forc_init.rs (hunk 1 above)
Comment (mitchmindtree) [reply forc/src/ops/forc_init.rs:10]: I've opened #872

**Review by mitchmindtree — APPROVED** [review]

**Review by mitchmindtree — CHANGES_REQUESTED** [review]
Oh looks like clippy's complaining

**Comment by ControlCplusControlV** [comment]
Seems to because of some unrelated files, want me to fix in this PR or a separate one?

**Comment by mitchmindtree** [comment]
Let's see if we can get away with just the one related to the diff of this PR, it looks like @vnepveu has already addressed the others in #867 (which I'll look at now!)

**Comment by ControlCplusControlV** [comment]
Clippy passed so maybe it just was that char thing of `/` vs "/"

**Review by mitchmindtree — APPROVED** [review]
