### PR TITLE
Generic impl selfs and associated fixes

### LINKED ISSUE #425: implement turbofish for enums and structs
My generics PR doesn't implement turbofish for enums `Option::<u64>`. It should not be difficult to implement. They are parsed but never actually ingested.

### LINKED ISSUE #814: Generic impl selfs don't really work
title

### LINKED ISSUE #827: Function bodies not monormophized
In particular cases, referencing a generic type produces an error. For example, this bit of code https://github.com/FuelLabs/sway/blob/cb9dd8bf92286dd1f6a6c8f018e78c78146c57d8/test/src/e2e_vm_tests/test_programs/size_of/src/main.sw#L28 should be able to find the size of the generic, but instead it gives an error.

I did some preliminary debugging and found something that may be related. If you have Sway like this:

```rust
fn the_same<T>(elem: T) -> T {
    let x: T = elem;
    x
}
```

Then inside of code gen for variable declarations, if you add a call to `println!("{:?}", crate::type_engine::look_up_type_id(var_decl.type_ascription);` inside of this function https://github.com/FuelLabs/sway/blob/323b4e17f7b32cd9709e1a5f29cb99e2da4e0171/sway-core/src/asm_generation/declaration/var_decl.rs#L10, you will see that the result is an `UnknownGeneric` which should not be the case.

### LINKED ISSUE #929: Type ascriptions throw away type information
Given this Sway code:

```rust
script;

struct DoubleIdentity<T, F> {
  first: T,
  second: F,
}

fn main() -> bool {
  let a: DoubleIdentity<u8, u8> = DoubleIdentity {
    first: 1u8,
    second: 2u8,
  };
  true
}
```

This gets tokenized via the `ident ~ type_params?` rule: https://github.com/FuelLabs/sway/blob/cfeeecc59f685d63ff5007d8e6ab0f3cea2cb74e/sway-core/src/sway.pest#L182

Which is then parsed and the type params are thrown away: https://github.com/FuelLabs/sway/blob/cfeeecc59f685d63ff5007d8e6ab0f3cea2cb74e/sway-core/src/type_engine/type_info.rs#L94

### LINKED ISSUE #1022: Bug with using unit in a turbofish
Per @adlerjohn  on slack, this fails:

```
error
  --> result/src/main.sw:12:31
   |
10 | 
11 | fn test_ok() {
12 |     let r = Result::Ok::<u64, ()>(42u64);
   |                               ^ Error parsing input: expected one of [ident]
13 | 
14 |     if ( !result_is_ok(r) || result_is_err(r)) {
   |
____

  Aborting due to 1 error.
Error: Failed to compile result
```

### PR DESCRIPTION
**Pull request by emilyaherbert**
- Closes #827
- Closes #814 
- Closes #929 
- Closes #1022 
- Closes #425 

Also:
- implement `PartialEq` for a large portion of the types in the compiler. I had to do this for an approach I was taking to solve a bug, but then it didn't end up being necessary in the end. I feel that the `PartialEq` impls are still useful though, so I left them in there.

Note:
- It turns out that it _was_ necessary to require generic params after the `impl`. This is so that the compiler is able to handle complex cases like:
```rust
struct Data<T, F> {
  first: T,
  second: F
}

impl<T, F> Data<Data<F, F>, Data<T, T>> {
  ...
}
```

### CODE REVIEW

**Review by adlerjohn — COMMENTED** [review]
Merge conflicts

File: sway-core/src/semantic_analysis/namespace.rs [hunk 1]
```diff
@@ -164,7 +164,7 @@ impl Namespace {
 #[derive(Clone, Debug, Default)]
 pub(crate) struct TraitMap {
     // This cannot be a HashMap because of how TypeInfo's are handled.
-    //
+    //
```
Comment (adlerjohn) [inline sway-core/src/semantic_analysis/namespace.rs:167]: Hmm the extra space doesn't seem to match how other comments look
```suggestion
    //
```

File: Cargo.lock [hunk 2]
```diff
@@ -111,15 +111,15 @@ dependencies = [
 
 [[package]]
 name = "anyhow"
-version = "1.0.56"
+version = "1.0.52"
```
Comment (adlerjohn) [inline Cargo.lock:114]: Revert changes to lockfile

**Review by adlerjohn — COMMENTED** [review]
Looks like CI is failing

File: sway-types/src/span.rs [hunk 3]
```diff
@@ -10,6 +10,13 @@ pub struct Span {
 }
 
 impl Span {
+    pub fn empty() -> Self {
+        Span {
+            span: pest::Span::new(" ".into(), 0, 0).unwrap(),
+            path: None,
+        }
+    }
+
```
Comment (otrho) [inline sway-types/src/span.rs:19]: We've needed this for a while!  I wonder if instead of a literally empty span we should use a message like "Source span not available." just to avoid weird error messages or something.

**Review by otrho — APPROVED** [review]
LGTM with a couple of nits.

I also feel like there must be a simpler way to get around the `PartialEq` problem for `TypeId` and especially for `Span` but I can't say what that might be.

**Review by adlerjohn — COMMENTED** [review]
The error reporting is off if I try to use a generic something non-generically, e.g. `let foo = Result;`. It points back to the declaration of `Result` instead of the line `let foo = Result;`.

**Comment by emilyaherbert** [comment]
> The error reporting is off if I try to use a generic something non-generically, e.g. `let foo = Result;`. It points back to the declaration of `Result` instead of the line `let foo = Result;`.

Can you give an example? Rust points to the declaration in this case: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=c70fb9e7abd0c156178aad6a5eda6d2b

**Comment by adlerjohn** [comment]
My bad, what I wrote here wasn't what I actually tested 😂

What I actually tested was
```sway
library foo;

struct DoubleIdentity<T, F> {
  first: T,
  second: F,
  third: u64
}

fn f(a: DoubleIdentity) {
}
```

Which produces:
```
error
 --> bad_generic/src/main.sw:3:1
  |
1 |   
2 |   
3 | / struct DoubleIdentity<T, F> {
4 | |   first: T,
5 | |   second: F,
6 | |   third: u64
7 | | }
  | |_^ Expected 2 type arguments, but instead found 0.
8 |   
9 |   fn f(a: DoubleIdentity) {
  |
____

error
 --> bad_generic/src/main.sw:3:1
  |
1 |   
2 |   
3 | / struct DoubleIdentity<T, F> {
4 | |   first: T,
5 | |   second: F,
6 | |   third: u64
7 | | }
  | |_^ Expected 2 type arguments, but instead found 0.
8 |   
9 |   fn f(a: DoubleIdentity) {
  |
____

error
 --> bad_generic/src/main.sw:3:1
  |
1 |   
2 |   
3 | / struct DoubleIdentity<T, F> {
4 | |   first: T,
5 | |   second: F,
6 | |   third: u64
7 | | }
  | |_^ Expected 2 type arguments, but instead found 0.
8 |   
9 |   fn f(a: DoubleIdentity) {
  |
____

error
 --> bad_generic/src/main.sw:3:1
  |
1 |   
2 |   
3 | / struct DoubleIdentity<T, F> {
4 | |   first: T,
5 | |   second: F,
6 | |   third: u64
7 | | }
  | |_^ Expected 2 type arguments, but instead found 0.
8 |   
9 |   fn f(a: DoubleIdentity) {
  |
____

  Aborting due to 2 errors.
```

File: sway-core/src/semantic_analysis/ast_node/declaration.rs [hunk 4]
```diff
@@ -162,16 +156,25 @@ impl TypedDeclaration {
...
+                    }
+                    builder.push_str(name.as_str());
+                    builder.push_str(": ");
+                    builder.push_str(
+                        &crate::type_engine::look_up_type_id(*type_ascription).friendly_type_str(),
+                    );
+                    builder.push_str(" = ");
+                    builder.push_str(&body.pretty_print());
+                    builder
+                }
```
[the remark this answers is not in the document]
Comment (emilyaherbert) [reply sway-core/src/semantic_analysis/ast_node/declaration.rs:177]: When there is a conditional involved I personally prefer to do this with a string builder.

File: sway-types/src/span.rs (hunk 3 above)
Comment (emilyaherbert) [reply sway-types/src/span.rs:19]: Good idea!

**Comment by emilyaherbert** [comment]
@adlerjohn behold 🔥 (not quite sure why there are two of the same, but I think that is unrelated to merging this feature)

Screen Shot 2022-03-24 at 11 05 23 PM

**Review by otrho — APPROVED** [review]
