### PR TITLE
Implement `if let` expressions and associated fixes

### LINKED ISSUE #624: Implement "if lets"
Implementing if-lets should allow for #579 to be implemented.

### LINKED ISSUE #817: Remove `OwnedTyped*` and use new Spans
Those `OwnedTypedStructField` and enum field types were implemented as a work around until spans didn't have reference lifetimes associated with them. Now that `Span`s don't do that, we can safely remove them.

### PR DESCRIPTION
**Pull request by sezna**
## Why?
As we don't have any form of destructuring, getting values out of enums is impossible. This hinders our progress in developing the standard library and basic demos -- primarily SwaySwap. 

## What?
This PR implements `if let` for enums, although not to complete parity with Rust's pattern matching. Some general fixes around generic types/enums/etc., are included in this PR as well.

## List O' Changes
1. Previously, `​​return​`​ statements inside of ​`​if`​​ expressions were not being type checked correctly. This PR fixes that.
2. Enum monomorphization was not implemented at all, this PR implements that.
3. Help text has been reintroduced to type errors.
4. Implements `if let` expressions, which compare an enum's tag and conditionally pull out its contents into a variable.
5. Improved error messages around generics: before 
image
afer
image
7. Improved dead code detection such that publicly exported enums don't warn that their variants are unused.
8. Allow type annotations for enum instantiations, i.e. `let x = Result::Ok::<u64, bool>(5u64)` 

## Remaining work
1. Generic `impl` blocks and trait interactions are still not there. This PR was big enough as is, so that'll be coming later. 
2. Arbitrary pattern destructuring is not implemented. This version of `if let` _only_ allows for destructuring the top-level enum. This is okay: `if let Result::Ok(val) = foo { .. }`, this is **not** okay: `if let Result::Ok(Option::Some(Enum::Variant(x, y, Struct { field, .. } ) ) ) = foo { .. }`

closes #817 
closes #624

### CODE REVIEW

**Review by adlerjohn — COMMENTED** [review]
CI failing. Can we convert to draft until working?

File: sway-core/src/asm_generation/expression/mod.rs [hunk 1]
```diff
@@ -276,48 +257,36 @@ pub(crate) fn convert_expression_to_asm(
...
-            namespace,
-            register_sequencer,
-            return_register,
-        ),
-        */
+            elem_to_access_num,
+        } => {
+            // sorry
+            let leaked_ix: &'static str = Box::leak(Box::new(elem_to_access_num.to_string()));
+            let access_ident = Ident::new_with_override(leaked_ix, elem_to_access_span.clone());
```
Comment (otrho) [inline sway-core/src/asm_generation/expression/mod.rs:265]: Obviously less than ideal.  Should we make an issue to not need `'static` strings for `Ident`?

File: sway-core/src/asm_generation/expression/structs.rs [hunk 2]
```diff
@@ -127,6 +126,7 @@ pub(crate) fn get_contiguous_memory_layout<N: Clone>(
         let stack_size = match ty.size_in_words(span) {
             Ok(o) => o,
             Err(e) => {
+                println!("`here3");
```
Comment (otrho) [inline sway-core/src/asm_generation/expression/structs.rs:129]:
```suggestion
```

File: sway-core/src/asm_generation/expression/structs.rs [hunk 3]
```diff
@@ -234,6 +234,7 @@ pub(crate) fn convert_fields_to_asm<N: Clone + std::fmt::Display>(
             Ok(o) => match o.size_in_words(span) {
                 Ok(o) => o,
                 Err(e) => {
+                    println!("`here4");
```
Comment (otrho) [inline sway-core/src/asm_generation/expression/structs.rs:237]:
```suggestion
```

File: sway-core/src/asm_generation/expression/subfield.rs [hunk 4]
```diff
@@ -93,12 +90,19 @@ pub(crate) fn get_subfields_for_layout(
...
+            })
             .collect::<Vec<_>>(),
         TypeInfo::Tuple(elems) => elems
             .iter()
             .enumerate()
-            .map(|(pos, elem)| (*elem, span.clone(), format!("{}", pos)))
+            .map(|(pos, elem)| {
+                // sorry
+                let leaked_ix: &'static str = Box::leak(Box::new(pos.to_string()));
+                let access_ident = Ident::new_with_override(leaked_ix, span.clone());
```
Comment (otrho) [inline sway-core/src/asm_generation/expression/subfield.rs:103]: "Sorry, not sorry."

File: sway-core/src/error.rs [hunk 5]
```diff
@@ -28,6 +28,7 @@ macro_rules! check_std_result {
         match $result_expr {
             Ok(res) => res,
             Err(e) => {
+                println!("in std result");
```
Comment (otrho) [inline sway-core/src/error.rs:31]:
```suggestion
```

File: sway-core/tests/sway_to_ir/mutable_struct.ir [hunk 6]
```diff
@@ -27,4 +27,4 @@ script {
 !5 = span !0 98 112
 !6 = span !0 109 111
 !7 = span !0 117 123
-!8 = span !0 124 125
+!8 = span !0 161 162
```
Comment (otrho) [inline sway-core/tests/sway_to_ir/mutable_struct.ir:30]: It looks like the span for reading a struct field was way off.  Weird.  I saw above in `optimize.rs` some changes related to the owned struct/enum stuff, so that must be it.

File: test/src/e2e_vm_tests/test_programs/chained_if_let/Forc.toml [hunk 7]
```diff
@@ -0,0 +1,5 @@
+[project]
+authors = ["Alexander Hansen"]
```
Comment (otrho) [inline test/src/e2e_vm_tests/test_programs/chained_if_let/Forc.toml:2]:
```suggestion
authors = ["Fuel Labs <contact@fuel.sh>"]
```

File: test/src/e2e_vm_tests/test_programs/chained_if_let_missing_branch/Forc.toml [hunk 8]
```diff
@@ -0,0 +1,6 @@
+[project]
+authors = ["Alexander Hansen"]
```
Comment (otrho) [inline test/src/e2e_vm_tests/test_programs/chained_if_let_missing_branch/Forc.toml:2]:
```suggestion
authors = ["Fuel Labs <contact@fuel.sh>"]
```

File: test/src/e2e_vm_tests/test_programs/chained_if_let/Forc.toml (hunk 7 above)
Comment (otrho) [reply test/src/e2e_vm_tests/test_programs/chained_if_let/Forc.toml:2]: How much do we care about this?  Most of the tests are `Fuel Labs`, I think @adlerjohn changed them all initially.

**Review by otrho — CHANGES_REQUESTED** [review]

**Comment by otrho** [comment]
Yikes, are we going to get `Forc.lock` conflicts like crazy from now on, or is this temporary?

**Comment by mitchmindtree** [comment]
> Yikes, are we going to get Forc.lock conflicts like crazy from now on, or is this temporary?

All of the `Forc.toml`s and `Forc.lock` files for the E2E tests were updated in #876 and shouldn't need to be updated in a PR like this (except for the new ones of course!). Conflicts in lock files should be no more common than conflicts related to changing version numbers in `Forc.toml`.

I think this is a unique case where the conflicts are potentially related to generating and committing lock files between #825 landing and #876 landing. I probably should have done #876 as a part of #825 to avoid this happening, but that PR was already massive enough! I would probably address this via a rebase onto master, but I know many prefer to avoid rebase and everyone has their own git wrangling strats :)

File: test/src/e2e_vm_tests/test_programs/chained_if_let/Forc.toml (hunk 7 above)
Comment (adlerjohn) [reply test/src/e2e_vm_tests/test_programs/chained_if_let/Forc.toml:2]: They should be Fuel Labs for consistency at the very least.

File: sway-core/src/asm_generation/expression/structs.rs (hunk 2 above)
Comment (sezna) [reply sway-core/src/asm_generation/expression/structs.rs:129]: haha this is embarrassing

File: sway-core/tests/sway_to_ir/mutable_struct.ir (hunk 6 above)
Comment (sezna) [reply sway-core/tests/sway_to_ir/mutable_struct.ir:30]: I removed the owned stuff since it was a holdover from when we had lifetimes associated with spans...those owned fields previously had no span data at all, so it makes sense they were off

File: sway-core/src/asm_generation/expression/mod.rs (hunk 1 above)
Comment (sezna) [reply sway-core/src/asm_generation/expression/mod.rs:265]: I'm not sure. I was debating the performance costs. We clone `Ident` a _lot_ throughout the compiler. I somewhat suspect that this leak is better for performance than using `String` everywhere for `Ident`. And using a scoped lifetime, like `<'sc>`, would be what we had before and nobody liked that.

This only happens specifically in these tuple accesses. I'm sure we can sort out a more localized solution that just updates the tuple access stuff. Maybe that's what the issue should be about.

**Review by otrho — APPROVED** [review]

**Review by otrho — APPROVED** [review]

**Review by mitchmindtree — APPROVED** [review]

**Comment by adlerjohn** [comment]
Do not merged until 0.6.1 is released https://github.com/FuelLabs/sway/pull/921
