### PR TITLE
Checking E2E contract test receipts

### LINKED ISSUE #484: Contract call failures are not failing the test suite appropriately.
This was a known shortcoming when writing it, but we should figure out a better solution now. In CI, the output of contract calls are not verified. The VM is returning this for a lot of tests:
```
[Panic { id: 0x0000000000000000000000000000000000000000000000000000000000000000, reason: 445105624603164672, pc: 3604, is: 464 }, ScriptResult { result: InstructionResult { reason: ContractNotFound, instruction: Instruction { op: 45, ra: 21, rb: 19, rc: 20, rd: 18, imm06: 18, imm12: 1298, imm18: 79122, imm24: 5584146 } }, gas_used: 0 }]
```

This is due to the contract IDs drifting from when we wrote the test. We should make it such that the harness validates the output of the executed scripts here: https://github.com/FuelLabs/sway/blob/master/test/src/e2e_vm_tests/mod.rs#L119

### PR DESCRIPTION
**Pull request by mohammadfawaz**
Closes #484, #685

### CODE REVIEW

**Comment by mohammadfawaz** [comment]
Looking for some help as to whether this is the right approach here.

File: test/src/e2e_vm_tests/mod.rs [hunk 1]
```diff
@@ -462,7 +462,12 @@ pub fn run(filter_regex: Option<regex::Regex>) {
         contract_ids.push(contract_id);
     }
     for name in projects {
-        harness::runs_on_node(name, &contract_ids);
+        assert!(!harness::runs_on_node(name, &contract_ids)
+            .iter()
+            .any(|r| matches!(
+                r,
+                fuel_tx::Receipt::Revert { .. } | fuel_tx::Receipt::Panic { .. }
```
Comment (sezna) [inline test/src/e2e_vm_tests/mod.rs:469]: Two things:

1. I prefer `all` instead of `!any` just due to personal cognitive overhead of logical negation.
2. Do we want to allow configurable expected return receipts instead of just checking that it didn't panic here? Allow the harness to expect a certain response from the contract call, like how we do with other script tests?

Comment (mohammadfawaz) [reply test/src/e2e_vm_tests/mod.rs:469]: We could probably check the return from main (so check the last return?). Checking that every contract call is correct is, I think, too much. I feel it's better to encourage asserts in the script instead as this would make modifying the test a lot simpler.

File: forc/src/ops/forc_run.rs [hunk 2]
```diff
@@ -56,39 +55,34 @@ pub async fn run(command: RunCommand) -> Result<()> {
...
             _ => &command.node_url,
         };
-        let child = try_send_tx(node_url, &tx, command.pretty_print).await?;
-        if command.kill_node {
-            if let Some(mut child) = child {
-                child.kill().await.expect("Node should be killed");
-            }
-        }
-        Ok(())
+        Ok(try_send_tx(node_url, &tx, command.pretty_print).await?)
```
Comment (mitchmindtree) [inline forc/src/ops/forc_run.rs:64]:
```suggestion
        try_send_tx(node_url, &tx, command.pretty_print).await
```

File: forc/src/ops/forc_run.rs [hunk 3]
```diff
@@ -56,39 +55,34 @@ pub async fn run(command: RunCommand) -> Result<()> {
...
-) -> Result<Option<Child>> {
+) -> Result<Vec<fuel_tx::Receipt>> {
     let client = FuelClient::new(node_url)?;
 
     match client.health().await {
-        Ok(_) => {
-            send_tx(&client, tx, pretty_print).await?;
-            Ok(None)
-        }
+        Ok(_) => Ok(send_tx(&client, tx, pretty_print).await?),
```
Comment (mitchmindtree) [inline forc/src/ops/forc_run.rs:76]:
```suggestion
        Ok(_) => send_tx(&client, tx, pretty_print).await,
```

Comment (mitchmindtree) [reply forc/src/ops/forc_run.rs:76]: I'm only spotting these because clippy complained about a similar thing on master yesterday :smiling_face_with_tear: I wonder why it's not catching these, or if I'm missing something :thinking:

File: forc/src/ops/forc_run.rs [hunk 4]
```diff
@@ -56,39 +55,34 @@ pub async fn run(command: RunCommand) -> Result<()> {
...
         let node_url = match &manifest.network {
             Some(network) => &network.url,
             _ => &command.node_url,
         };
-        let child = try_send_tx(node_url, &tx, command.pretty_print).await?;
-        if command.kill_node {
-            if let Some(mut child) = child {
-                child.kill().await.expect("Node should be killed");
-            }
-        }
```
Comment (mitchmindtree) [inline forc/src/ops/forc_run.rs:70]: Good spot! I guess the `Child` was left over from the days where `forc run` would spin up a node?

**Review by mitchmindtree — APPROVED** [review]
Looks good! My comments are mostly optional, will happily re-approve if you want to address them but don't mind either way.

File: forc/src/ops/forc_run.rs (hunk 3 above)
Comment (otrho) [reply forc/src/ops/forc_run.rs:76]: :thinking:

File: forc/src/ops/forc_run.rs (hunk 4 above)
Comment (mohammadfawaz) [reply forc/src/ops/forc_run.rs:70]: Thanks! That would make sense!

**Review by mitchmindtree — APPROVED** [review]

File: test/src/e2e_vm_tests/mod.rs (hunk 1 above)
Comment (mohammadfawaz) [reply test/src/e2e_vm_tests/mod.rs]: So, I modified this a big to also allow checking for the last `return` (i.e. second to last entry in the vector of receipts). I don't like this very much as I prefer to get access to `ProgramState` but I can't do that from a vector of receipts. Matching on receipts directly is also a big annoying because each variant requires specifying many parameters. So, I require matching on returned integers directly.

**Review by sezna — APPROVED** [review]
