### PR TITLE
const_eval can try (recursively) compile unresolved decls

### LINKED ISSUE #2151: Const evaluator fails when initializing a `const` with another `const`
Example:
```rust
script;

const ZERO_B256 = 0x0000000000000000000000000000000000000000000000000000000000000000;
const KEY = ZERO_B256;

fn main() { }
```
Error:
```console
3 | const ZERO_B256 = 0x0000000000000000000000000000000000000000000000000000000000000000;
4 | const KEY = ZERO_B256;
  |             ^^^^^^^^^ Could not evaluate initializer to a const declaration.
```

cc @vaivaswatha

### PR DESCRIPTION
**Pull request by vaivaswatha**
When the constant evaluator is executing, and it encounters a declaration that hasn't been added to "global_constants" yet, it can try and recursively compile that declaration.

Note that constant declarations are processed (const evaluated) in an arbitrary order and hence dependences aren't resolved. This change just dynamically resolves unmet dependences (when possible).

Closes #2151

### CODE REVIEW

File: sway-core/src/ir_generation/const_eval.rs [hunk 1]
```diff
@@ -20,14 +22,66 @@ use sway_types::{ident::Ident, span::Spanned};
...
+    pub module: Module,
+    pub module_ns: Option<&'a namespace::Module>,
+    pub public_only: bool,
+    pub lookup: fn(&mut LookupEnv, &Ident) -> Result<Option<Value>, CompileError>,
+}
+
+pub fn compile_const_decl(
+    env: &mut LookupEnv,
+    name: &Ident,
+) -> Result<Option<Value>, CompileError> {
```
Comment (otrho) [inline sway-core/src/ir_generation/const_eval.rs:36]: What does returning `Ok(None)` signify?  It succeeded but there's no value?

**Review by otrho — COMMENTED** [review]
Looks good.  I'm leaning towards suggesting `LookupEnv` be a const evel context and all those functions which take a `lookup` be methods (which take a `&mut self`... so what's the difference?)

Is this still meant to be a draft?

File: sway-core/src/ir_generation/const_eval.rs (hunk 1 above)
Comment (vaivaswatha) [reply sway-core/src/ir_generation/const_eval.rs:36]: This function does two things
1. Provides a lookup.
2. Recursive entry to the actual const evaluator. 

In the case of a lookup not happening, it isn't the duty of this function to return an error, but just say `None`. In case the call to the actual evaluator fails, it passes on that error.

**Review by otrho — APPROVED** [review]

**Comment by r-sitko** [comment]
@vaivaswatha 
By the way, if this PR resolves #2151 can it also make change in sway-lib-std/src/constants.sw to use ZERO_B256 const in BASE_ASSET_ID initialization? There is a TODO comment left to do this when #2151 is resolved.

**Review by r-sitko — COMMENTED** [review]
By the way, if this PR resolves https://github.com/FuelLabs/sway/issues/2151 maybe it can also make change in sway-lib-std/src/constants.sw to use ZERO_B256 const in BASE_ASSET_ID initialization? There is a TODO comment left to do this when https://github.com/FuelLabs/sway/issues/2151 is resolved.

**Review by sezna — APPROVED** [review]
