### PR TITLE
Evaluate const decls before storage decls

### LINKED ISSUE #2424: Initializing a storage slot with a `const` doesn't seem to work just yet
I know that the const evaluator is still WIP, but this is a simple case that should probably be easy to support:
```rust
contract;

const C1 = 42;

storage {
    x: u64 = C1,
}
```
We currently get the following error:
```console
4 |
5 | storage {
6 |     x: u64 = C1,
  |              ^^ Could not evaluate initializer to a const declaration.
7 | }
  |
```

Also, the error is not great because we're not actually trying to initialize a `const` declaration here. The error should be tailored for storage initializers.

### PR DESCRIPTION
**Pull request by vaivaswatha**
This allows storage decls to use const decls for initialization.

I'm not very happy with this change because it introduces sway-ir stuff earlier on. But looks like that was already happening when we tried to const-evaluate storage initializers. This change only adds evaluating the module const decls as well early on, so that they can be used when evaluating the storage initializers.

Closes #2424

### CODE REVIEW

File: sway-core/src/metadata.rs [hunk 1]
```diff
@@ -14,7 +14,7 @@ use std::{collections::HashMap, path::PathBuf, sync::Arc};
 ///! indices repeatedly.
 
 #[derive(Default)]
-pub(crate) struct MetadataManager {
+pub struct MetadataManager {
```
Comment (otrho) [inline sway-core/src/metadata.rs:17]: Why does this need to leak out of the crate?

File: test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/basic_storage/json_storage_slots_oracle.json [hunk 2]
```diff
@@ -1,42 +1,46 @@
 [
   {
     "key": "02dac99c283f16bc91b74f6942db7f012699a2ad51272b15207b9cc14a70dbae",
-    "value": "6161610000000000000000000000000000000000000000000000000000000000"
+    "value": "6161000000000000000000000000000000000000000000000000000000000000"
```
Comment (otrho) [inline test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/basic_storage/json_storage_slots_oracle.json:4]: Are these changes all expected?

**Review by otrho — COMMENTED** [review]
I'm still not really a fan of using IR to evaluate stuff in the compiler, I feel like it's a hack, but it was the easiest solution for getting something quickly.  So this change doesn't really change much, but ideally we have a better compiler specific evaluator one day.

File: sway-core/src/metadata.rs (hunk 1 above)
Comment (vaivaswatha) [reply sway-core/src/metadata.rs:17]: Without this, I get `can't leak crate-private type` in `compile.rs`.

File: test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/basic_storage/json_storage_slots_oracle.json (hunk 2 above)
Comment (vaivaswatha) [reply test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/basic_storage/json_storage_slots_oracle.json:4]: > Are these changes all expected?

Yes. Because I added another storage field, the storage indices changed, and hence the keys.

File: sway-core/src/ir_generation.rs [hunk 3]
```diff
@@ -1,4 +1,4 @@
-mod compile;
+pub mod compile;
```
Comment (otrho) [inline sway-core/src/ir_generation.rs:1]: So maybe this should be `pub(crate)`?

**Review by otrho — APPROVED** [review]
