### PR TITLE
fix: fix manifest formatter in `forc fmt`

### LINKED ISSUE #671: Manifest formatter doesn't format manifest file
Running `forc fmt` doesn't format the manifest file, even though `forc fmt --check` will report incorrect formatting.

### PR DESCRIPTION
**Pull request by vnepveu**
This PR fixes a dumb bug where the formatter didn't actually format the code. 
It also formats all tests manifests using said formatter.
This closes #671.

### CODE REVIEW

**Review by adlerjohn — APPROVED** [review]
utACK, but will defer to @sezna.

**Review by adlerjohn — CHANGES_REQUESTED** [review]
My suggestion is to revert the actual running of the formatter changes, as it will result in merge conflicts with e.g. #683, and is orthogonal to fixing the bug. A separate PR should be opened after #683 lands, and ideally after #687 is fixed.

File: forc/src/ops/forc_fmt.rs [hunk 1]
```diff
@@ -66,24 +66,23 @@ fn format_after_build(command: FormatCommand) -> Result<(), FormatError> {
...
+                if !command.check {
+                    format_file(&manifest_file, &formatted_content)?;
+                } else if formatted_content != file_content {
+                    if !contains_edits {
+                        contains_edits = true;
                     }
+                    eprintln!("\nManifest Forc.toml improperly formatted");
+                    display_file_diff(&file_content, &formatted_content)?;
+                } else {
+                    eprintln!("\nManifest Forc.toml properly formatted")
```
Comment (sezna) [inline forc/src/ops/forc_fmt.rs:85]: I don't think we should use `eprintln`, i.e. error print line, if the manifest is actually properly formatted.

File: forc/src/ops/forc_fmt.rs [hunk 2]
```diff
@@ -66,24 +66,23 @@ fn format_after_build(command: FormatCommand) -> Result<(), FormatError> {
...
-                            contains_edits = true;
-                        }
-                        eprintln!("\nManifest Forc.toml improperly formatted");
-                        display_file_diff(&file_content, &formatted_content)?;
-                    } else {
-                        format_file(&manifest_file, &formatted_content)?;
+                if !command.check {
+                    format_file(&manifest_file, &formatted_content)?;
+                } else if formatted_content != file_content {
+                    if !contains_edits {
```
Comment (sezna) [inline forc/src/ops/forc_fmt.rs:79]: I know you didn't introduce this line of code, but:
```rust
if !contains_edits {
    contains_edits = true;
}
```

could just be:
```rust
contains_edits = true;
```

In fact, due to the tautological nature of this statement, I'm not sure why it is necessary.

File: forc/src/ops/forc_fmt.rs [hunk 3]
```diff
@@ -66,24 +66,23 @@ fn format_after_build(command: FormatCommand) -> Result<(), FormatError> {
...
+                        contains_edits = true;
                     }
+                    eprintln!("\nManifest Forc.toml improperly formatted");
+                    display_file_diff(&file_content, &formatted_content)?;
```
Comment (sezna) [inline forc/src/ops/forc_fmt.rs:83]: If the command mode is `check`, we explicitly want to return a non-zero exit code back to the terminal. This will be handled automatically if we return an `Err` out of `main()`. Could you confirm that a non-zero exit code is being returned in the case where the toml is incorrectly formatted in `--check` mode?

**Review by sezna — CHANGES_REQUESTED** [review]

File: forc/src/ops/forc_fmt.rs (hunk 2 above)
Comment (vnepveu) [reply forc/src/ops/forc_fmt.rs:79]: yes I wondered the same but am still to shy to change legacy code haha. Will be more affirmed in the future.

File: forc/src/ops/forc_fmt.rs (hunk 3 above)
Comment (vnepveu) [reply forc/src/ops/forc_fmt.rs:83]: This is handled by the `contains_edit` boolean

**Review by adlerjohn — APPROVED** [review]

**Review by sezna — APPROVED** [review]
