### PR TITLE
CompileError::ContractIdConstantNotAConstDecl

### LINKED ISSUE #6841: Eliminate CompileError::ContractIdConstantNotAConstDecl
The error `CompileError::ContractIdConstantNotAConstDecl` is only used in `contract_helpers.rs`, and is only thrown if the typecheck of the `CONTRACT_ID` declaration fails. Since this declaration is generated by the compiler, this typecheck should never fail, and if it does it should be an internal compiler error instead.

### PR DESCRIPTION
**Pull request by mo-hak**
## Description
In contract_helpers.rs, replaced the ContractIdConstantNotAConstDecl error with an Internal compiler error since this represents an impossible state that should never occur in normal operation.
In error.rs, removed the now unused ContractIdConstantNotAConstDecl error variant and its corresponding span implementation.
The changes make sense because:
The error was only used in one place where it represented an impossible state
If that state is ever reached, it indicates a bug in the compiler itself rather than user error
Using an internal compiler error will make it clearer that this is a compiler bug that needs to be fixed if it ever occurs
fix #6841 

## Checklist

- [x] I have linked to any relevant issues.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation where relevant (API docs, the reference, and the Sway book).
   - [ ] If my change requires substantial documentation changes, I have [requested support from the DevRel team](https://github.com/FuelLabs/devrel-requests/issues/new/choose)
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added (or requested a maintainer to add) the necessary `Breaking*` or `New Feature` labels where relevant.
- [x] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [x] I have requested a review from the relevant team or maintainers.

### CODE REVIEW

**Review by jjcnn — DISMISSED** [review]

File: sway-core/src/semantic_analysis/namespace/contract_helpers.rs [hunk 1]
```diff
@@ -105,9 +105,10 @@ fn bind_contract_id_in_root_module(
...
         TyAstNodeContent::Declaration(_) => Ok(namespace.root()),
         _ => Err(
-            handler.emit_err(CompileError::ContractIdConstantNotAConstDecl {
-                span: const_item_span,
-            }),
+            handler.emit_err(CompileError::Internal(
+                "Contract ID declaration did not typecheck to a declaration, which should be impossible",
+                const_item_span,
+            )),
         ),
```
Comment (IGI-111) [inline sway-core/src/semantic_analysis/namespace/contract_helpers.rs:112]: This should probably be an if-let.

Comment (mo-hak) [reply sway-core/src/semantic_analysis/namespace/contract_helpers.rs:112]: Ah yes, you are right. Let me modify and commit it !

**Review by jjcnn — APPROVED** [review]

**Review by IGI-111 — APPROVED** [review]
