### PR TITLE
Fixes missing error on type unification.

### LINKED ISSUE #5162: Generics and associated types clash
The following script compiles just fine, but shouldn't.

```sway
script;

trait TypeTrait {
    type T;

    fn method() -> Self::T;
} {
    fn method2<T>() -> T {
        Self::method()
    }
}

fn main() -> u32 {
    1
}
```

It would be nice to remove the "Self" treatment from `replace_self_type` (https://github.com/FuelLabs/sway/blob/103095e1f8332a0bbfaf0f5627973d7ea118050c/sway-core/src/type_system/id.rs#L166) because it conflicts with PR #4962 which is almost done.

### LINKED ISSUE #5212: Generic impl trait compiling when it shouldn't.
The following code compiles when it shouldn't.

```rust
pub trait MyFrom<T> {
    fn from(b: T) -> Self;
}

impl<T,U> MyFrom<T> for U {
    fn from(i: T) -> U {
        i
    }
}
```

### PR DESCRIPTION
**Pull request by esdrubal**
## Description

While using generic blanket implementation no error was thrown when another type other than the generic blanket expected type was used.

This was caused by the typechecker being too permissive in UnknownGeneric unification. The fix changes the unifier to handle unification with the expected self and generics as special cases.

Closes #5212
Closes #5162

## Checklist

- [x] I have linked to any relevant issues.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation where relevant (API docs, the reference, and the Sway book).
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added (or requested a maintainer to add) the necessary `Breaking*` or `New Feature` labels where relevant.
- [x] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [x] I have requested a review from the relevant team or maintainers.

### CODE REVIEW

File: sway-core/src/type_system/engine.rs [hunk 1]
```diff
@@ -20,6 +20,12 @@ pub struct TypeEngine {
     id_map: RwLock<HashMap<TypeInfo, TypeId>>,
 }
 
+enum UnifyKind {
```
Comment (IGI-111) [inline sway-core/src/type_system/engine.rs:23]: This needs extensive doccomments to explain that the differences between the unification modes is.

**Comment by IGI-111** [comment]
If we're going to have multiple modes like this, it might be a good idea to refactor the unifier to work like `UnifyCheck`.

**Review by IGI-111 — APPROVED** [review]

**Review by JoshuaBatty — APPROVED** [review]
