### PR TITLE
Fix `storage` blocks

### LINKED ISSUE #1755: `storage` blocks not formatted very well
Example:
```rust
storage {
    map1: StorageMap<u64,
    bool>, map2: StorageMap<u64,
    u8>, map3: StorageMap<u64,
    u16>, map4: StorageMap<u64,
    u32>, map5: StorageMap<u64,
    u64>, map6: StorageMap<u64,
    (b256, u8, bool) >, map7: StorageMap<u64,
    Struct>, map8: StorageMap<u64,
    Enum>, map9: StorageMap<u64,
    str[33]>, map10: StorageMap<u64,
    [b256;
    3]>, map11: StorageMap<bool,
    u64>, map12: StorageMap<u8,
    u64>, map13: StorageMap<u16,
    u64>, map14: StorageMap<u32,
    u64>, map15: StorageMap<(b256,
    u8, bool), u64 >, map16: StorageMap<Struct,
    u64>, map17: StorageMap<Enum,
    u64>, map18: StorageMap<str[33],
    u64>, map19: StorageMap<[b256;
    3],
    u64>, 
}
```
From https://github.com/FuelLabs/sway/pull/1754/files. I expect each `StorageMap` to get its own line.

### PR DESCRIPTION
**Pull request by eureka-cpu**
Closes #1755 

Updates `Punctuated` to not remove an opening brace accidentally when there are no items to be formatted. Also did some code quality stuff along the way to solving this bug. Adds a test suite for `storage` blocks and organizes the module.

### CODE REVIEW

**Review by JoshuaBatty — DISMISSED** [review]

File: sway-fmt-v2/src/utils/language/punctuated.rs [hunk 1]
```diff
@@ -18,62 +18,65 @@ where
...
-        match formatter.shape.code_line.line_style {
-            LineStyle::Normal => {
-                let value_pairs = &self.value_separator_pairs;
-                for (type_field, punctuation) in value_pairs.iter() {
-                    type_field.format(formatted_code, formatter)?;
-                    punctuation.format(formatted_code, formatter)?;
-                    write!(formatted_code, " ")?;
-                }
+        if self.value_separator_pairs.is_empty() && self.final_value_opt.is_none() {
+        } else {
```
Comment (mitchmindtree) [inline sway-fmt-v2/src/utils/language/punctuated.rs:22]: Rather than:
```rust
        if self.value_separator_pairs.is_empty() && self.final_value_opt.is_none() {
        } else {
```
Could be
```rust
        if !(self.value_separator_pairs.is_empty() && self.final_value_opt.is_none()) {
```

**Review by mitchmindtree — DISMISSED** [review]
Other than one minor unimportant nit, LGTM!

File: sway-fmt-v2/src/utils/language/punctuated.rs (hunk 1 above)
Comment (eureka-cpu) [reply sway-fmt-v2/src/utils/language/punctuated.rs:22]: That line is so that if the block is completely empty we do nothing, if we have something we don't want to execute that block

Comment (eureka-cpu) [reply sway-fmt-v2/src/utils/language/punctuated.rs:22]: OH, i see it now
I'm the dumb

**Review by mitchmindtree — APPROVED** [review]

**Review by JoshuaBatty — APPROVED** [review]
