### PR TITLE
Fix for `storage` initializers in `sway-fmt-v2`

### LINKED ISSUE #2279: `sway-fmt-v2` drops storage initializers
While disallowing storage variables from not being initialized (https://github.com/FuelLabs/sway/pull/2278/files#), I had to change some tests in `sway-fmt-v2` by adding dummy initializers to them. However, it seems that the initializers get dropped after formatting. I know `sway-fmt-v2` is a WIP but just wanted to bring this up in case storage initializers are not tracked.

Here's an example with initializers:
```rust
contract;

struct Type1 {
    x: u64,
    y: u64,
}

struct Type2 {
    w: b256,
    z: bool,
}

storage {
    var1: Type1 = Type1 {
        x: 0,
        y: 0,
    },
    var2: Type2 = Type2 {
        w: 0x0000000000000000000000000000000000000000000000000000000000000000,
        z: false,
    },
}

abi StorageExample {
    #[storage(write)]fn store_something();
    #[storage(read)]fn get_something() -> (u64, u64, b256, bool);
}

impl StorageExample for Contract {
    #[storage(write)]fn store_something() {
        storage.var1.x = 42;
        storage.var1.y = 77;
        storage.var2.w = 0x1111111111111111111111111111111111111111111111111111111111111111;
        storage.var2.z = true;
    }

    #[storage(read)]fn get_something() -> (u64, u64, b256, bool) {
        (storage.var1.x, storage.var1.y, storage.var2.w, storage.var2.z)
    }
}
```

### PR DESCRIPTION
**Pull request by eureka-cpu**
Closes #2279 

This handles formatting of `storage` initializers with the example provided by @mohammadfawaz

### CODE REVIEW

File: sway-fmt-v2/src/items/item_storage.rs [hunk 1]
```diff
@@ -150,7 +150,13 @@ fn format_storage(
         let mut value_pairs_iter = fields.value_separator_pairs.iter().peekable();
         for field in value_pairs_iter.clone() {
             // storage_field
-            field.0.format(formatted_code, formatter)?;
+            write!(
+                formatted_code,
+                "{}{} {}",
+                field.0.name.span().as_str(),
+                field.0.colon_token.span().as_str(),
+                field.0.ty.span().as_str(),
```
Comment (kayagokalp) [inline sway-fmt-v2/src/items/item_storage.rs:158]: Maybe we should use `ty` formatting here rather than the raw `str` coming from `span` 🤔

File: sway-fmt-v2/src/utils/punctuated.rs [hunk 2]
```diff
@@ -64,15 +64,17 @@ impl Format for StorageField {
...
+        formatter: &mut Formatter,
     ) -> Result<(), FormatterError> {
         write!(
             formatted_code,
-            "{}{} {}",
+            "{}{} {} {} ",
             self.name.span().as_str(),
             self.colon_token.span().as_str(),
-            self.ty.span().as_str()
+            self.ty.span().as_str(),
```
Comment (kayagokalp) [inline sway-fmt-v2/src/utils/punctuated.rs:74]: ^ same `ty` formatting stuff applies here too 🙌

**Review by kayagokalp — COMMENTED** [review]
Left a small nit regarding `ty` formatting, otherwise looks good to me. Thanks for handling this as this will also get #2311's CI 🟢 .

File: sway-fmt-v2/src/items/item_storage.rs (hunk 1 above)
Comment (eureka-cpu) [reply sway-fmt-v2/src/items/item_storage.rs:158]: right you are!

**Review by kayagokalp — APPROVED** [review]
🚀 🚀

**Review by mitchmindtree — APPROVED** [review]
