### PR TITLE
`forc-tx`: Improve error handling using `thiserror`. Fix `panic!`ing version/help output.

### LINKED ISSUE #3886: `forc tx --help` prints help successfully but within a `panic!` message
This is due to the current way we attempt to parse the trailing chain of `input`s and `output`s.

Until this is addressed, we'll need to omit this from the Sway book's Forc Plugins section as the mdbook-forc-documenter plugin uses the `--help` output to generate docs.

This is further motivation for #3804, ideally so that we can just call `Command::parse` at the top-level like a normal clap application and get regular coloured help output.

### PR DESCRIPTION
**Pull request by mitchmindtree**
## Description

This introduces a `Command::parse` constructor that emulates the behaviour of the `clap` parse constructor in order to provide a more consistent clap-like CLI experience. For context, we cannot use the generated `parse` command due to limitations in clap's ability to handle trailing subcommands as mentioned in #3804.

We switch to using `thiserror` in the library in order to allow for handling error cases (necessary for the new `parse` constructor) and to provide cleaner, more detailed error cause traces.

The help and version output no longer panic, and now behave like regular clap applications. Closes #3886.

Also adds an example command invocation to the end of the `--help` output.

## Checklist

- [x] I have linked to any relevant issues.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation where relevant (API docs, the reference, and the Sway book).
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added (or requested a maintainer to add) the necessary `Breaking*` or `New Feature` labels where relevant.
- [x] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [x] I have requested a review from the relevant team or maintainers.

### CODE REVIEW

**Review by bingcicle — APPROVED** [review]
utACK

File: forc-plugins/forc-tx/src/lib.rs [hunk 1]
```diff
@@ -306,29 +306,231 @@ pub struct OutputContractCreated {
...
+/// Errors that can occur during transaction input conversion.
+#[derive(Debug, Error)]
+pub enum ConvertInputError {
+    #[error("failed to read message data from {path:?}")]
+    MessageDataRead {
+        path: PathBuf,
+        #[source]
+        err: std::io::Error,
+    },
+    #[error("failed to read predicate from {path:?}")]
```
Comment (bingcicle) [inline forc-plugins/forc-tx/src/lib.rs:386]:
```suggestion
    #[error("failed to read --predicate from {path:?}")]
```

Should we be consistent with printing the error here? Above, in the `BytecodeRead` error, we are printing the option flag as is, but here, we're not showing `--predicate`. IMO in this case, explicitly showing the option flag works better since it's a long command.

**Review by bingcicle — CHANGES_REQUESTED** [review]

**Review by JoshuaBatty — APPROVED** [review]

**Review by bingcicle — APPROVED** [review]
utACK

**Review by otrho — APPROVED** [review]
utACK
