### PR TITLE
Fix type check and inference issues in references, structs, and enums

### LINKED ISSUE #5559: Internal compiler error with references, `Option`, and type ascription
This code fails with `Internal compiler error: Verification failed: Struct field type mismatch.`.

```Sway
script;
 
fn main() {
  let r: &Option<u8> = &Option::Some(1);
}
```

The reason is the fact that type-checking of references wrongly removes the type annotation from the `TypeCheckContext` by setting it to `TypeInfo::Unknow` instead of extracting the referenced type and passing it as type annotation.

### LINKED ISSUE #5583: Incorrect error messages in enum instantiation
The following example generates incorrect error messages:

```Sway
script;

enum MyOption {
    Some: bool,
    None: (),
}

enum MyOtherOption {
    NoSome: bool,
    None: (),
}

main() {
    let _: MyOption = Option::Some(123);
           //                      ^^^ Mismatched types.
           // expected: bool      // WRONG: Expectation is coming from a type that is not `Option`.
           // found:    numeric.
           // help: Enum instantiator must match its declared variant type.

    let _: MyOtherOption = Option::Some(123);
           //                      ^^^^ Variant "Some" does not exist on enum "MyOtherOption"
           // WRONG: We are type-checking `Option` and `Some` do exist.

    let _: Option<u8> = Option::Some(123u64);
          //            ^^^^^^^^^^^^^^^^^^^^ Mismatched types.
          // expected: u8   // WRONG: Should be `Option<u8>`.
          // found:    u64.   // WRONG: Should be `Option<u64>`.
          // help: Variable declaration's type annotation does not match up with the assigned expression's type.

}
```

The reason for the first two misleading messages is taking the LHS enum as the type annotation source for the RHS without checking that it is the same enum type.

### LINKED ISSUE #5598: Wrong type unification of enums and structs in case of name and structural equality
This example compiles, treating the two enums named `E` as the same type, and two struct `S` respectively.

```
// lib_a.sw
library;
pub enum E { X: u8, }
pub struct S { pub x: u8, }

...

// lib_b.sw
library;
pub enum E { X: u8, }
pub struct S { pub x: u8, }

...

// main.sw
script; 

mod lib_a;
mod lib_b;

use ::lib_a::E as Lib_A_E;
use ::lib_a::S as Lib_A_S;

use ::lib_b::E as Lib_B_E;
use ::lib_b::S as Lib_B_S;

fn main() {
  let _: Lib_A_E = Lib_B_E::X(123);     // Two different enums unified.
  let _: Lib_A_S = Lib_B_S { x: 123 };  // Two different structs unified.
}
```

### PR DESCRIPTION
**Pull request by ironcev**
## Description

This PR:
- fixes #5559, #5597, and #5492 by removing the `TypeInfo::Unknown` and providing the required contextual information to type checking of referencing, dereferencing, `if`, and `match` expressions respectively. The contextual information provided is taken from the `ctx.type_annotation()` but always adapted according to the semantics of the type-checked expression.
- fixes #5583 and #5581 by combining the contextual information coming from the `ctx.type_annotation()` with the one coming from the enum and struct instantiation and declaration.
- fixes #5598 by forcing the name-based and not structure-based identity. In other words, two enums or structs are considered equal only if they whole `call_path`s are equal. Up to now, we were expecting only the enum or struct _names_ to be equal, which was treating types with same names and structures (variants or fields) as equal although they were defined in different modules.

The PR also introduces parsing of references to mutable values (`&mut T`). Since this addition does not overlap with the above bug fixes, it was left as is, and can be fully ignored during the review. Other changes related to references to mutable values are removed from the code from type-checking onward to make this PR only fixing the issues. Continuation on references to mutable values will be done in a separate PR.

Closes #5559, #5597, #5492, #5583, #5581, #5598.

## Checklist

- [x] I have linked to any relevant issues.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation where relevant (API docs, the reference, and the Sway book).
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added (or requested a maintainer to add) the necessary `Breaking*` or `New Feature` labels where relevant.
- [x] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [x] I have requested a review from the relevant team or maintainers.

### CODE REVIEW

File: sway-core/src/semantic_analysis/ast_node/declaration/declaration.rs [hunk 1]
```diff
@@ -54,14 +54,29 @@ impl TyDecl {
...
+                //       an integer, RHS should properly unify or type check should fail.
+                //       Remove this special case as a part of the initiative of improving type inference.
                 // Integers are special in the sense that we can't only rely on the type of `body`
                 // to get the type of the variable. The type of the variable *has* to follow
                 // `type_ascription` if `type_ascription` is a concrete integer type that does not
                 // conflict with the type of `body` (i.e. passes the type checking above).
                 let return_type = match &*type_engine.get(type_ascription.type_id) {
                     TypeInfo::UnsignedInteger(_) => type_ascription.type_id,
-                    _ => body.return_type,
+                    _ => match &*type_engine.get(body.return_type) {
```
Comment (xunilrj) [inline sway-core/src/semantic_analysis/ast_node/declaration/declaration.rs:67]: I am finding this part a little bit confused. 

If a variable declaration has type ascription, the `TyVarDecl` below should always use the type ascription of the variable.

And after that, we need to do is unify and check the type ascription with the return of the init expression and give the best error/warning possible, right?

That will also "kill" the special case for `ints` here.

Comment (ironcev) [reply sway-core/src/semantic_analysis/ast_node/declaration/declaration.rs:67]: Yes you are right. But at this stage I was already overwhelmed with the PR that took way too long exactly because I was tracking issues that were popping up and not limiting the scope of this PR.

Knowing that if I change the current behavior, there will very likely be additional errors popping from the remaining cases of expressions that can be on the RHS but do not comply with the provided `ctx.type_annotation()` but rather use `TypeInfo::Unknown` internally, I've opted for just writing the above TODOs at the moment and let this be solved properly as a part of #5562 step 4. Also, the `TyExpression::type_check()` currently do not return `Err` if the unification fails (#5606), etc.

That's why I fear touching this as a part of this PR could lead to additional effort hard to estimate upfront. And since this PR is actually blocking for #5562 I am still of the opinion to solve this particular case as a part of the #5562 step 4. 

Is this ok for you?

**Review by IGI-111 — APPROVED** [review]
LGTM insofar as we can resolve those TODOs in a later PR

File: sway-core/src/semantic_analysis/ast_node/declaration/declaration.rs (hunk 1 above)
Comment (ironcev) [reply sway-core/src/semantic_analysis/ast_node/declaration/declaration.rs:67]: Silence implies consent :smile: so I am resolving this remark. It will be done as part of #5562.

**Review by xunilrj — APPROVED** [review]
