### PR TITLE
fix: forc-deploy asks for password before checking if the wallet exists

### LINKED ISSUE #6703: forc-deploy asks password for non-existing wallet
## Problem

Currently if the user does not have a wallet, forc-deploy offers them to create a new one. We will also offer them to import if they have one already created with #6680. But even there is no wallet at the default path the ask for password is invoked before checking this situation so we end up asking for a password for a wallet that does not exists. 

```bash
...
  Confirming transactions [deploy final-contract]
             Network: https://testnet.fuel.network
             Wallet: /Users/kayagokalp/.fuel/wallets/.wallet
✔ Wallet password · ****
? Could not find a wallet at "/Users/kayagokalp/.fuel/wallets/.wallet", would you like to create a new one? [y/N]:  (y/n) ›
```

## Fix

This is a basic logic error and the order of invoking password prompt and checking/creating a new wallet should be switched.

### PR DESCRIPTION
**Pull request by kayagokalp**
## Description
closes #6703 and unblocks #6680.

Forc-deploy was asking for a password without checking if a wallet exists or not and the check for existence was happening after the password prompt. This meant we were asking for a password even when the wallet does not exists.

Below examples are taken in a system where the wallet does not exists at the default path (a fresh system):
### Before

```bash
...
  Confirming transactions [deploy final-contract]
             Network: https://testnet.fuel.network
             Wallet: /Users/kayagokalp/.fuel/wallets/.wallet
✔ Wallet password · ****
? Could not find a wallet at "/Users/kayagokalp/.fuel/wallets/.wallet", would you like to create a new one? [y/N]:  (y/n) ›
```

### After

```bash
...
  Confirming transactions [deploy final-contract]
             Network: https://testnet.fuel.network
? Could not find a wallet at "/Users/kayagokalp/.fuel/wallets/.wallet", would you like to create a new one? [y/N]:  (y/n) ›
```

### CODE REVIEW

File: forc-plugins/forc-client/src/op/deploy.rs [hunk 1]
```diff
@@ -1002,6 +1002,11 @@ async fn setup_deployment_account(
     } else if let Some(arn) = &command.aws_kms_signer {
         SignerSelectionMode::AwsSigner(arn.clone())
     } else {
+        // Check if we have a wallet in the default path
+        // If there is one we will ask for the password
+        // If not we will ask the user to either create a new one or import one
```
Comment (kayagokalp) [inline forc-plugins/forc-client/src/op/deploy.rs:1007]:
```suggestion
        // If not we will ask the user to either create a new one
```

**Review by zees-dev — APPROVED** [review]
Lgtm 👍

**Review by sdankel — DISMISSED** [review]
lgtm, thanks!

**Comment by kayagokalp** [comment]
Updated and it should be good now :)

The failing test assumed it was testing wrong password but it was not. Due to the same bug that is being solved with this PR, cli was asking a password for a wallet that does not exists. Updated the test, as the relevant section in the code also states we need to be able to override the default path for tests to test the happy path as well. I'll try to look into it next week 👌

**Comment by kayagokalp** [comment]
Thinking about this I am curious what happens if you run cargo -t locally after this change if you a have a wallet locally will the test fail 🤔 We should probably think about overriding the default path for tests so that the tests ensure reproducability

**Review by zees-dev — APPROVED** [review]

**Review by sdankel — APPROVED** [review]
